## calcRules are generated by starting with declRules and then fracturing based on top-down processing

## {top,end,latent} rules are just lists of pointers/shallow copies of calcRules
## {stoch,dep} rules are just lists of pointers/shallow copies of nodeRules

## key functions:
## exclude(rhsRule,declRule) -> rhsRule (0 or more)
## fracture(dep, calcRule, stochParent, parentID) -> calcRule (0 or more)

## have rulesListClass to hold multiple rules?
## rulesListClass could contain the counter of the number of included rules

## nodeRuleClass is base class for declRuleClass, calcRuleClass, rhsRuleClass

nodeRuleClass <- R6Class(
    classname = "nodeRuleClass",
    portable = FALSE,
    public = list(
        context = NULL,
        expr = NULL,  
        constants = NULL,
        ID = numeric(),
        varName = character(),
        numIndices = numeric(),
        allRules = NULL,
        externalRules = NULL, # indexing for the nodes
        internalRules = NULL, # indexing for components, if multivariate nodes
        numExternalRules = numeric(0),
        numInternalRules = numeric(0),
        index2setID = NULL,

        initialize = function(expr, ID, context = modelContextClass$new(), constants = list()) {
            ## not clear everything will go through if no indexing
            varName <<- ifelse(length(expr) > 1, deparse(expr[[2]]), deparse(expr))
            ID <<- ID
            context <<- context
            expr <<- expr
            constants <<- constants

            ## Note: this is awkward to go into the data structures and modify them

            ## We'll use graphRules, though only have a single side of declaration.
            allRules <<- makeGraphIndexRules(expr, expr, context, constants)
            index2setID <<- allRules$indexSets$LHSindex2setID
            isConstant <- sapply(allRules$indexRules, is, "indexRuleClass_constant")
            
            numIndices <<- length(allRules$indexSets$LHSindex2setID)

            ## Treat constants as internal rules that don't relate to indexing over nodes.
            ## Need to relate constant rule types to indexing; constant rules are in order of constant indices.
            constantIndices <- allRules$indexSets$LHSindex2setID == 0
            
            externalRules <<- allRules
            externalRules$indexRules[isConstant] <<- NULL
            externalRules$indexSets$LHSindex2setID <<-
                externalRules$indexSets$LHSindex2setID[!constantIndices]

            internalRules <<- allRules
            internalRules$indexRules[!isConstant] <<- NULL
            internalRules$indexSets$numSets <<- 0
            internalRules$indexSets$LHSindex2setID <<-
                internalRules$indexSets$LHSindex2setID[constantIndices]
            
            numExternalRules <<- length(externalRules$indexRules)
            numInternalRules <<- length(internalRules$indexRules)

        },
        
        ## Generate nodeRange from a varRange (or another nodeRange)
        apply = function(varRange = NULL) {
            if(is.null(varRange)) {   ## user wants full range for the variable
                varRange <- getFullRange()
            } 
            if(numExternalRules) {
                externalRange <- applyGraphIndexRules(varRange, externalRules)
            } else externalRange <- NULL # varRangeClass$new(list(nimbleModel:::indexRange_empty()))
            if(numInternalRules) {
                internalRange <- applyGraphIndexRules(varRange, internalRules)
            } else internalRange <- NULL # varRangeClass$new(list(nimbleModel:::indexRange_empty()))
            if((!is.null(externalRange) && externalRange$isEmpty()) || (!is.null(internalRange) &&  internalRange$isEmpty())) {
                if(!is.null(externalRange))
                    externalRange <- varRangeClass$new(lapply(seq_len(numExternalRules), function(i) indexRange_empty()))
                if(!is.null(internalRange))
                    internalRange <- varRangeClass$new(lapply(seq_len(numInternalRules), function(i) indexRange_empty()))
            }
            result <- nodeRangeClass$new(varName, externalRange, internalRange, index2setID, self)
            return(result)
        },

        getFullRange = function() {
            extent <- lapply(seq_along(allRules$indexRules), function(idx)
                allRules$indexRules[[idx]]$get_max())

            ## Case of no indexing, e.g. x ~ dnorm(0,1)
            if(!length(extent[[1]]))
                return(varRangeClass$new(list(indexRange_none()), varName = varName))

            maxes <- rep(0, length(index2setID))
            cnt <- 1
            cntConstant <- 0
            constants <- which(index2setID == 0)
            for(i in seq_along(extent)) {
                if(is(allRules$indexRules[[i]], "indexRuleClass_constant")) {
                    cntConstant <- cntConstant + 1
                    maxes[constants[cntConstant]] <- extent[[i]]
                } else {
                    maxes[index2setID == i] <- extent[[i]] 
                }
            }
            
            return(applyGraphIndexRules(
                    varRangeClass$new(lapply(seq_len(numIndices),
                                             function(i) indexRange(
                                                             substitute(1:MAX, list(MAX = maxes[i])))),
                                      varName = varName),
               allRules))
        }
    )
)

declRuleClass <- R6Class(
    classname = "declRuleClass",
    portable = FALSE,
    inherit = nodeRuleClass,
    public = list(
        stoch = logical(),
        originalIndexRules = NULL, # determines original indexing (based on context)
        decl = NULL,
        calculate = NULL,  ## generic function for calculation

        initialize = function(decl, ID, context = modelContextClass$new(), constants = list()) {
            ## Set up rules that operate on the indexing of the nodes and on
            ## the internal indexing of the elements of a node.
            stoch <<- decl[[1]] == '~'
            decl <<- decl
            super$initialize(decl[[2]], ID, context = context, constants = constants)
            
            originalIndexRules <<- originalIndexRuleClass$new(expr, context, constants)
            calcFun <<- genCalcFun(decl, context)
        },


        genCalcFun = function(decl, context) {
            ## using context$indexVarNames, substitute "idx[1]", "idx[2]", etc.
            ## then generate a function with the decl code in it.
            ## e.g.
            ## function(idx) {
            ##   logProb_y[idx[2]+1, idx[1]] <- dnorm(mu[idx[2]], 1)
            ## }
            ## will need to deal with the various complexities we currently deal with - alt params, truncation, etc.
        }
        
    )
)

calcRuleClass <- R6Class(
    classname = "calcRuleClass",
    portable = FALSE,
    inherit = nodeRuleClass,
    public = list(
        canonicalRange = NULL,
        declRule = NULL,  # multiple calcRules can share a declRule and its density function

        stochParent = NA,
        stochDep = NA,
        ## touchedDown = FALSE,
        ## touchedUp = FALSE,
        parents = numeric(),
        children = numeric(),

        top = FALSE,
        end = NA,

        sortID = NULL,

        initialize = function(declRule = NULL, expr = NULL, ID, context, constants = list()) {
            ## If LHS is NULL, just use declRule internalRange

            ## This wastes some calculation by redoing the internal/external rule stuff
            ## even though at least the internal stuff already done in the declRule
            if(is.null(expr)) expr <- declRule$expr
            super$initialize(expr, ID, context = context, constants = constants)

            ## Full range, for use with calculate applied to full variable.

            ## 1:Inf fails if ijni
            ## use getFullRange()
            
            ## canonicalRule <- makeGraphIndexRules(expr, expr, context, constants)
            ## The following fails in ijni type case where 1:Inf is actually expanded in a matrix.
            ## canonicalRange <<- applyGraphIndexRules(
            ##    varRangeClass$new(lapply(seq_along(allRules$indexSets$LHSindex2setID),
            ##        function(i) indexRange(quote(1:Inf)))), allRules)

            ## For testing we are doing fracturing on generic nodeRules rather than declRules,
            ## so declRule not available. Revisit whether it's ok to leave this as is.
            if(!is.null(declRule))
                canonicalRange <<- declRule$getFullRange()
            context <<- context
            declRule <<- declRule
        },

        ## calcRuleClass$apply generates a nodeRange
        
        ## Generate calcRange given a varRange (including a nodeRange).
        generate_calcRange = function(inputRange = NULL) {
            if(is.null(inputRange))
                inputRange <- canonicalRange            
            indexingRange <- declRule$originalIndexRules$apply(inputRange)
            if(indexingRange$isEmpty())
                return(NULL)
            result <- calcRangeClass$new(varName, indexingRange, declRule$calcFun, sortID)
            return(result)
        },

        get = function(varRange = NULL, type) {
            ## type is 'end', 'latent', etc.
            ## returns the embedded nodeRange (or subset of it if provided a varRange) that corresponds to 'type'
        },
        
        is_type = function(type) {
            switch(type,
                end = return(end),
                top = return(top),
                latent = return(!end && !top),
                stop("Invalid type ", type)
            )
        },

        set = function(type) {
            switch(type,
                end = end <<- TRUE,
                top = top <<- TRUE,
                ## latent = latent <<- TRUE,
                stochParent = stochParent <<- TRUE,
                stochDep = stochDep <<- TRUE,
                stop("Invalid type ", type)
                )
            return(TRUE)
        },

        unset = function(type) {
            switch(type,
                end = end <<- FALSE,
                top = top <<- FALSE,
                ## latent = latent <<- FALSE,
                stochParent = stochParent <<- FALSE,
                stochDep = stochDep <<- FALSE,
                stop("Invalid type ", type)
                )
            return(FALSE)
        },

        checkAnyRHS = function() {
            vars <- all.vars(declRule$decl[[3]])
            if(all(vars %in% c(names(declRule$constants), declRule$context$indexVarNames)))
                return(FALSE) else return(TRUE)
        },

        setParents = function(IDs) {
            parents <<- c(parents, IDs)
        },
        
        setChildren = function(IDs) {
            children <<- c(children, IDs)
        },

        unsetParents = function(IDs) {
            parents <<- parents[!parents %in% IDs]
        },
        
        unsetChildren = function(IDs) {
            children <<- children[!children %in% IDs]
        },

        setStochDep = function(calcRules) {
            if(!is.na(stochDep))
                return(stochDep)
            if(!length(children)) {
                return(unset('stochDep'))
            }
            ## First check if any children are stochastic
            stoch <- sapply(children, function(idx)
                calcRules[[idx]]$declRule$stoch)
            if(any(stoch)) {
                return(set('stochDep'))
            } else {   ## If necessary check if deterministic children have stoch dependents
                idx <- 1
                while(idx <= length(stoch)) {
                    ## Walk down the tree as needed.
                    if(calcRules[[children[[idx]]]]$setStochDep(calcRules)) {
                        return(set('stochDep'))
                    }
                    idx <- idx + 1
                }
            }
            return(unset('stochDep'))
        },
        
        setStochParent = function(calcRules) {
            if(!is.na(stochParent))
                return(stochParent)
            if(!length(parents)) {
                return(unset('stochParent'))
            }
            ## First check if any parents are stochastic
            stoch <- sapply(parents, function(idx)
                calcRules[[idx]]$declRule$stoch)
            if(any(stoch)) {
                return(set('stochParent'))
            } else {   ## If necessary check if deterministic children have stoch dependents
                idx <- 1
                while(idx <= length(stoch)) {
                    ## Walk up the tree as needed.
                    if(calcRules[[parents[idx]]]$setStochParent(calcRules)) {
                        return(set('stochParent'))
                    }
                    idx <- idx + 1
                }
            }
            return(unset('stochParent'))
        },

        setSortID = function(calcRules, ancestors = NULL) {
            ## Bottom-up determination (since want maximal ties amongst potentially most-numerous data nodes)
            ## Easiest here to have bottom-most rules have sortID of 1, since have to start with bottom.
            if(!length(children)) {
                sortID <<- 1
                return(sortID)
            }
            if(any(children %in% ancestors))
                stop("Cycle found in model graph. NIMBLE does not allow cyclic models.")
            sortID <<- max(sapply(children, function(i)
                calcRules[[i]]$setSortID(calcRules, c(ancestors, ID)))) + 1
##                calcRules[[i]]$setSortID(calcRules[[i]](calcRules))) + 1)
            return(sortID)
        }
        
    )
)

calcRangeClass <- R6Class(
    classname = "calcRangeClass",
    portable = FALSE,
    public = list(
        varName = NULL,
        indexingRange = NULL,
        sortID = NULL,
        initialize = function(varName, indexingRange, calcFun, sortID) {
            varName <<- varName
            indexingRange <<- indexingRange
            calcFun <<- calcFun  ## note that calcFun itself is not vectorized
            sortID <<- sortID
        },

        ## Generic calculate function that crosses the indexRanges in the indexingRange (a varRange)
        ## and extracts the original indice to feed into calculate nodeFunction
        ## that operates on set of scalar indices.
        
        ## Will need to figure out how this is going to get compiled.
        ## Will there be a permanent C++ version?
        ## How will indexingRange be compiled?
        ## This is a sketch and hasn't been debugged...
        calculate = function() {
            numRanges <- length(indexingRange$indexRanges)
            index <- numeric(length(indexingRange$indexID_2_rangeID))  ## vector to hold the original index values
            indexRange_lengths <- sapply(indexingRange$indexRanges, indexRange_numRows)
            indexPositions <- indexingRange$rangeID_2_indexID
            nestedLengths <- sapply(seq_len(numRanges), function(i) prod(indexRange_lengths[(i+1):numRanges]))
                                    
            for(item in prod(indexRange_lengths)) {
                for(irIndex in seq_len(numRanges)) {
                    ## Determine nested indexing from unrolled indexing
                    if(irIndex == seq_len(numRanges)) {
                        elementIdx <- 1 + (item-1) %% indexRange_lengths[irIndex]
                    } else {
                        elementIdx <- 1 + (item-1) %/% nestedLengths[irIndex]
                    }
                    index[indexPositions[irIndex]] <- indexRange_getItem(indexingRange$indexRanges[[irIndex]], elementIdx)
                }
                self$calcFun(index)  ## scalar calculation
            }

        }
    )
)

## nodeRangeClass

## Holds a collection of like nodes (same declaration, but not (I think) necessarily same graph role or same sort ID).

## example: y[i, 1:5] ~ dmnorm() has:
## externalRange: first index, over selected nodes
## internalRange: 1:5
## e.g., could represent as y[1:3, (1:5)] where () indicates internal grouping

## Convert to subclass of varRangeClass
## need to figure out exactly how indexRanges, internalIndexRanges and externalIndexRanges would be handled/created,
## ideally without redundancy.
nodeRangeClass <- R6Class(
    classname = "nodeRangeClass",
    portable = FALSE,
    inherit = varRangeClass,
    public = list(
        declRule = NULL,
        boolExternalIndexRanges = NULL,
        numExternalIndexRanges = NULL,

        initialize = function(varName,
                              externalRange,
                              internalRange,
                              index2setID,
                              declRule) {

            numExternalIndexRanges <<- length(externalRange$indexRanges)
            
            ## This is convoluted to determine the indexID_2_rangeID and rangeID_2_indexID
            ## and then pass these into varRange initialization where indexID_2_rangeID will be recalculated
            ## from rangeID_2_indexID.
           
            indexID_2_rangeID <<- rep(0, length(index2setID))
            # if(sum(index2setID != 0) != length(externalRange$indexID_2_rangeID)) browser()
            indexID_2_rangeID[index2setID != 0] <<- externalRange$indexID_2_rangeID
            indexID_2_rangeID[index2setID == 0] <<- internalRange$indexID_2_rangeID +
                numExternalIndexRanges
            if(length(indexID_2_rangeID)) {
                rangeID_2_indexID <<- lapply(seq_len(max(indexID_2_rangeID)),
                                             function(x) which(indexID_2_rangeID == x))
            } else rangeID_2_indexID <- list()
            super$initialize(indexInfo = c(externalRange$indexRanges, internalRange$indexRanges),
                             indexOrders = rangeID_2_indexID,
                             varName = varName)
            boolExternalIndexRanges <<- c(rep(TRUE, numExternalIndexRanges),
                                          rep(FALSE, length(internalRange$indexRanges)))

            declRule <<- declRule  ## pointer to governing declRule

        },
        
        expandNames = function() {
            ## Expand externalRange into full matrix (crossed if necessary), keeping full internal
            ## indexing for each individual node.
            ## TODO: allow user to request all elements and compact/expanded
            nc <- length(declRule$index2setID)  # might be, e.g., 0 1 0 2 3 or 0 1 0 2 1
            str <- paste0(name, "[")

            nodeInfo <- lapply(indexRanges, function(x) {
                if(identical(attr(x, 'rangeType'), 'sequence'))
                    result <- seq(x[[1]][[1]], x[[1]][[2]]) else result <- x[[1]]
                if(!is.matrix(result)) result <- matrix(result, ncol = 1)
                return(result)
            })
            expanded <- do.call(expand.grid, lapply(nodeInfo, function(x) {
                if(is.matrix(x)) 1:nrow(x) else 1:length(x)
            }))

            internalInfo <- lapply(indexRanges[!boolExternalIndexRanges], function(x) {
                if(identical(attr(x, 'rangeType'), 'sequence'))
                    return(deparse(substitute(X:Y, list(X = x[[1]][[1]], Y = x[[1]][[2]]))))
                return(x)
            })

            ## Mark column position within indexRanges of the externalRange.
            colID <- as.list(rep(1, length(nodeInfo)))
            ## Mark position within internal- and node-related indices.
            idxInternal <- 1
            idxNode <- 1
            
            for(i in 1:nc) {
                if(i > 1)
                    str <- paste0(str, ", ")
                if(declRule$index2setID[i] == 0) {
                    str <- paste0(str, internalInfo[[idxInternal]])
                    idxInternal <- idxInternal + 1
                } else {
                    rangeIdx <- indexID_2_rangeID[indexID_2_rangeID <= numExternalIndexRanges][idxNode] ## which indexRange is being used
                    str <- paste0(str, nodeInfo[[rangeIdx]][expanded[ , rangeIdx], colID[[rangeIdx]]])
                    colID[[rangeIdx]] <- colID[[rangeIdx]] + 1  ## index through columns of the indexRange_matrix 
                    idxNode <- idxNode + 1
                }
            }
            str <- paste0(str, "]")
            return(str)
        }
    )
)

nodeRange_isEqual <- function(nr1, nr2) {
    ok <- identical(nr1$indexID_2_rangeID, nr2$indexID_2_rangeID) &&
        identical(nr1$indexRanges, nr2$indexRanges) &&
        identical(nr1$boolExternalIndexRanges, nr2$boolExternalIndexRanges) 
    return(ok)
}


## Fracture a LHS rule based on dependencies of another LHS rule, produced from applyGraphIndexRules,
## passed through a nodeRule to produce a nodeRange
## Result can be:
##  - original rule
##  - subset of original rule and a rule created from the fracturingRange
##  - two subsets of original rule and a rule created from the fracturingRange (when dealing with a sequence that is split)

## LHSrule will be a calcRule, not a declRule
## fracture() should take in ID of parent calcRule that generated the fracturingRange via getDeps
## assign the parents to any rules that are fractured
fracture <- function(LHSrule, fracturingRange, currentID = 0, parentRule = NULL, currentRules = NULL) {
    ## presume fracturingRange is a nodeRange, so has external/internal split consistent with LHS rule
    ## but it could be that we pass in a varRange and then use nodeRule$apply to get the nodeRange
    ## this also means that fracturingRange is the 'intersection' as it shouldn't contain anything not in the LHSrule

    ## TODO: do we need to guard against being provided a fracturingRange that is a nodeRange that contains elements not
    ## part of the LHSrange?
    
    ## stochParent <- !is(parentRule, "rhsRuleClass") && (parentRule$declRule$stoch || parentRule$stochParent)

    ## Get full nodeRange of the rule.
    LHSrange <- LHSrule$apply()

    if(!is(fracturingRange, 'nodeRangeClass'))
        fracturingRange <- LHSrule$apply(fracturingRange)

    if(fracturingRange$isEmpty()) 
        return(NULL)

    if(nodeRange_isEqual(LHSrange, fracturingRange)) {
        if(!is.null(parentRule)) {  # if parent is not RHS
            parentRule$setChildren(LHSrule$ID)
            LHSrule$setParents(parentRule$ID)
        }
        return(NULL)
    }

    ## Indices for internalRange should be identical, so just check/fracture those for external
    boolIdenticalIndices <- sapply(seq_along(LHSrange$indexID_2_rangeID), function(idx)
        isTRUE(all.equal(LHSrange$indexRanges[[LHSrange$indexID_2_rangeID[idx]]],
                          fracturingRange$indexRanges[[fracturingRange$indexID_2_rangeID[idx]]])))

    ## boolIdenticalIndices <- sapply(LHSrange$indexID_2_rangeID, function(idx)
    ##     isTRUE(all.equal(LHSrange$indexRanges[[idx]],
    ##                       fracturingRange$indexRanges[[idx]])))

    nonIdenticalIndices <- which(!boolIdenticalIndices)
    
    expr <- LHSrule$expr
    singleContexts <- LHSrule$context$singleContexts
  
    if(length(nonIdenticalIndices) == 1) {
        ## Handle simple cases where need only fracture one index
        LHS <- LHSrange$indexRanges[[LHSrange$indexID_2_rangeID[nonIdenticalIndices]]]
        frac <- fracturingRange$indexRanges[[LHSrange$indexID_2_rangeID[nonIdenticalIndices]]]
        
        typeLHS <- attr(LHS, "rangeType")
        typeFrac <- attr(frac, "rangeType")

        focalContext <- sapply(names(singleContexts), function(nm)
            nm %in% all.vars(expr[[2+nonIdenticalIndices]]))

        ## If matrix involved, need to be dealt with so as to create an arbitrary rule.
        if(typeLHS == "matrix" || typeFrac == "matrix") {
            valsLHS <- switch(typeLHS,
                              matrix = LHS[[1]],
                              scalar = LHS[[1]],
                              sequence = LHS[[1]][[1]]:LHS[[1]][[2]],
                              stop("typeLHS not found")
                              )
            valsFrac <- switch(typeFrac,
                              matrix = frac[[1]],
                              scalar = frac[[1]],
                              sequence = frac[[1]][[1]]:frac[[1]][[2]],
                              stop("typeFrac not found")
                              )
            valsLHS <- valsLHS[!valsLHS %in% valsFrac]

            ## Modify LHSrule expr and context to insert vector of relevent values.
            newSingleContexts1 <- singleContexts[!focalContext]
            newSingleContexts2 <- singleContexts[!focalContext]

            newSingleContexts1[[length(newSingleContexts1)+1]] <- modelSingleContext(
                               indexVarExpr = quote(.newidx),
                indexRangeExpr = substitute(1:L, list(L = length(valsLHS))))

            newSingleContexts2[[length(newSingleContexts2)+1]] <- modelSingleContext(
                               indexVarExpr = quote(.newidx),
                indexRangeExpr = substitute(1:L, list(L = length(valsFrac))))

            newcode <- paste0(".idx", nonIdenticalIndices, "[.newidx]") 
            expr[[nonIdenticalIndices+2]] <- parse(text = newcode[1])[[1]]
         
            ## Replace any constants related to a previously processed index.
            constants1 <- list(valsRHS)
            constants2 <- list(valsFrac)
            names(constants1) <- paste0(".idx", nonIdenticalIndices)
            names(constants2) <- paste0(".idx", nonIdenticalIndices)
            oldConstants <- LHSrule$constants
            oldConstants[names(oldConstants) %in% names(constants1)] <- NULL

            resultRule <- calcRuleClass$new(LHSrule$declRule, expr, as.character(currentID + 1), context = modelContextClass$new(newSingleContexts1),
                                            constants = list(constants1, oldConstants))

            fracturingRule <- calcRuleClass$new(LHSrule$declRule, expr, as.character(currentID + 2), context = modelContextClass$new(newSingleContexts2),
                                                constants = list(constants2, oldConstants))

            result <- list(fracturingRule, resultRule)
        } else {  # seq+seq or seq+scalar
            if(typeFrac == "scalar")   # process as a sequence
                frac <- indexRange(substitute(A:A, list(A = frac[[1]])))
            if(typeLHS == "scalar") stop("Not expecting LHS to be a scalar")  ## scalar LHS either fully intersected or not intersected
          
            if(frac[[1]][1] == LHS[[1]][[1]] || frac[[1]][[2]] == LHS[[1]][[2]]) {
                ## Shrink existing sequence
                if(frac[[1]][[1]] == LHS[[1]][[1]]) 
                    LHS[[1]][[1]] <- frac[[1]][[2]]+1 else LHS[[1]][[2]] <- frac[[1]][[1]]-1

                newSingleContexts1 <- singleContexts[!focalContext]
                newSingleContexts2 <- singleContexts[!focalContext]

                newSingleContexts1[[length(newSingleContexts1)+1]] <- modelSingleContext(
                    indexVarExpr = quote(.newidx),
                    indexRangeExpr = substitute(A:B, list(A = LHS[[1]][[1]], B = LHS[[1]][[2]])))

                newSingleContexts2[[length(newSingleContexts2)+1]] <- modelSingleContext(
                    indexVarExpr = quote(.newidx),
                    indexRangeExpr = substitute(A:B, list(A = frac[[1]][[1]], B = frac[[1]][[2]])))

                expr[[nonIdenticalIndices+2]] <- newSingleContexts1[[length(newSingleContexts1)]]$indexVarExpr

                fracturingRule <- calcRuleClass$new(LHSrule$declRule, expr, as.character(currentID + 1), context = modelContextClass$new(newSingleContexts2))
                resultRule <- calcRuleClass$new(LHSrule$declRule, expr, as.character(currentID + 2), context = modelContextClass$new(newSingleContexts1))

                result <- list(fracturingRule, resultRule)
            } else {
                ## Split an existing sequence 
                newSingleContexts1 <- singleContexts[!focalContext]
                newSingleContexts2 <- singleContexts[!focalContext]
                newSingleContexts3 <- singleContexts[!focalContext]

                expr1 <- expr2 <- expr3 <- expr
                newSingleContexts1[[length(newSingleContexts1)+1]] <- modelSingleContext(
                    indexVarExpr = quote(.newidx),
                    indexRangeExpr = substitute(A:B, list(A = frac[[1]][[1]], B = frac[[1]][[2]])))
                expr1[[nonIdenticalIndices+2]] <- newSingleContexts1[[length(newSingleContexts1)]]$indexVarExpr

                newSingleContexts2[[length(newSingleContexts2)+1]] <- modelSingleContext(
                    indexVarExpr = quote(.newidx),
                    indexRangeExpr = substitute(A:B, list(A = LHS[[1]][[1]], B = frac[[1]][[1]]-1)))
                expr2[[nonIdenticalIndices+2]] <- newSingleContexts2[[length(newSingleContexts2)]]$indexVarExpr

                newSingleContexts3[[length(newSingleContexts3)+1]] <- modelSingleContext(
                    indexVarExpr = quote(.newidx),
                    indexRangeExpr = substitute(A:B, list(A = frac[[1]][[2]]+1, B = LHS[[1]][[2]])))
                expr3[[nonIdenticalIndices+2]] <- newSingleContexts3[[length(newSingleContexts3)]]$indexVarExpr
               
                fracturingRule <- calcRuleClass$new(LHSrule$declRule, expr1, as.character(currentID + 1), context = modelContextClass$new(newSingleContexts1))
                resultRule1 <- calcRuleClass$new(LHSrule$declRule, expr2, as.character(currentID + 2), context = modelContextClass$new(newSingleContexts2))
                resultRule2 <- calcRuleClass$new(LHSrule$declRule, expr3, as.character(currentID + 3), context = modelContextClass$new(newSingleContexts3))

                result <- list(fracturingRule, resultRule1, resultRule2)
            }
        }
    } else {     ## unroll, exclude, create new arbitrary rule based on all non-identical indices
        unrolledLHS <- LHSrange$getIndexRangeMatrix(nonIdenticalIndices)
        unrolledFrac <- fracturingRange$getIndexRangeMatrix(nonIdenticalIndices)

        lhsAsChar <- do.call(paste, as.data.frame(unrolledLHS[[1]]))
        fracAsChar <- do.call(paste, as.data.frame(unrolledFrac[[1]]))

        remaining <- !lhsAsChar %in% fracAsChar
        mat1 <- unrolledLHS[[1]][remaining, , drop = FALSE]
        mat2 <- unrolledLHS[[1]][!remaining, , drop = FALSE]

        focalContext <- sapply(names(singleContexts), function(nm)
            nm %in% unlist(lapply(2+nonIdenticalIndices, function(x) all.vars(expr[[x]]))))

        if(sum(!focalContext)) {
            newSingleContexts1 <- singleContexts[!focalContext]
            newSingleContexts2 <- singleContexts[!focalContext]
        } else newSingleContexts1 <- newSingleContexts2 <- list()

        newSingleContexts1[[length(newSingleContexts1) + 1]] <- modelSingleContext(
                               indexVarExpr = quote(.newidx),
            indexRangeExpr = substitute(1:L, list(L = nrow(mat1))))

        newSingleContexts2[[length(newSingleContexts2) + 1]] <- modelSingleContext(
                               indexVarExpr = quote(.newidx),
            indexRangeExpr = substitute(1:L, list(L = nrow(mat2))))

        newcode <- paste0(".idx", nonIdenticalIndices, "[.newidx]")
        for(i in seq_along(nonIdenticalIndices)) 
            expr[[nonIdenticalIndices[i]+2]] <- parse(text = newcode[i])[[1]]
        
        constants1 <- lapply(seq_len(ncol(mat1)), function(i) mat1[,i])
        names(constants1) <- paste0(".idx", nonIdenticalIndices)
        constants2 <- lapply(seq_len(ncol(mat2)), function(i) mat2[,i])
        names(constants2) <- paste0(".idx", nonIdenticalIndices)
        oldConstants <- LHSrule$constants
        oldConstants[names(oldConstants) %in% names(constants1)] <- NULL

      
        fracturingRule <- calcRuleClass$new(LHSrule$declRule, expr, as.character(currentID + 1), context = modelContextClass$new(newSingleContexts2),
                                        constants = c(constants2, oldConstants))
        resultRule <- calcRuleClass$new(LHSrule$declRule, expr, as.character(currentID + 2), context = modelContextClass$new(newSingleContexts1),
                                        constants = c(constants1, oldConstants))

        result <- list(fracturingRule, resultRule)
    }

    names(result) <- sapply(result, function(rule) rule$ID)
    
    if(!is.null(parentRule)) {  # if parent is not RHS
        result[[1]]$setParents(parentRule$ID)
        parentRule$setChildren(result[[1]]$ID)
        sapply(result, function(rule) rule$setParents(LHSrule$parents))
        ## if(stochParent) result[[1]]$set('stochParent')

        ## Update children of parents of the fractured rule
        newChildren <- sapply(result, function(x) x$ID)
        names(newChildren) <- NULL
        tmp <- sapply(LHSrule$parents, function(idx)
            currentRules[[idx]]$setChildren(newChildren))
        tmp <- sapply(LHSrule$parents, function(idx) currentRules[[idx]]$unsetChildren(LHSrule$ID))
    }
    ## Remove fractured rule as parent of its children
    ## The new fractured rules will be added in as parents when they are used as fracturers,
    ## later in looping over calcRules.
    tmp <- sapply(LHSrule$children, function(idx)
        currentRules[[idx]]$unsetParents(LHSrule$ID))
    return(result)
}

      
