## calcRules are generated by starting with declRules and then fracturing based on top-down processing

## {top,end,latent} rules are just lists of pointers/shallow copies of calcRules
## {stoch,dep} rules are just lists of pointers/shallow copies of nodeRules

## key functions:
## exclude(rhsRule,declRule) -> rhsRule (0 or more)
## fracture(dep, calcRule, stochParent, parentID) -> calcRule (0 or more)

## have rulesListClass to hold multiple rules?
## rulesListClass could contain the counter of the number of included rules

## nodeRuleClass is base class for declRuleClass, calcRuleClass, rhsRuleClass

nodeRuleClass <- R6Class(
    classname = "nodeRuleClass",
    portable = FALSE,
    public = list(
        context = NULL,
        expr = NULL,  
        constants = NULL,
        ID = numeric(),
        varName = character(),
        numIndices = numeric(),
        allRules = NULL,
        externalRules = NULL, # indexing for the nodes
        internalRules = NULL, # indexing for components, if multivariate nodes
        numExternalRules = numeric(0),
        numInternalRules = numeric(0),
        index2setID = NULL,

        initialize = function(expr, ID, context = modelContextClass$new(), constants = list()) {
            if(length(expr) > 1)
                varName <<- expr[[2]] else varName <<- expr   ## not clear everything will go through if no indexing

            ID <<- ID
            context <<- context
            expr <<- expr
            constants <<- constants

            ## Note: this is awkward to go into the data structures and modify them

            ## TODO: modify allRules to be a graphRule
            allRules <<- makeGraphIndexRules(expr, expr, context, constants)
            allRules$constraints <- list()
            index2setID <<- allRules$indexSets$LHSindex2setID
            isConstant <- sapply(allRules$indexRules, is, "indexRuleClass_constant")
            
            numIndices <<- length(allRules$indexSets$LHSindex2setID)

            ## Treat constants as internal rules that don't relate to indexing over nodes.
            ## Need to relate constant rule types to indexing; constant rules are in order of constant indices.
            constantIndices <- allRules$indexSets$LHSindex2setID == 0
            
            externalRules <<- allRules
            externalRules$indexRules[isConstant] <<- NULL
            externalRules$indexSets$LHSindex2setID <<-
                externalRules$indexSets$LHSindex2setID[!constantIndices]

            internalRules <<- allRules
            internalRules$indexRules[!isConstant] <<- NULL
            internalRules$indexSets$numSets <<- 0
            internalRules$indexSets$LHSindex2setID <<-
                internalRules$indexSets$LHSindex2setID[constantIndices]
            
            numExternalRules <<- length(externalRules$indexRules)
            numInternalRules <<- length(internalRules$indexRules)

        },
        
        ## Generate nodeRange from a varRange (or another nodeRange)
        apply = function(inputRange = NULL) {
            if(is.null(inputRange)) {   ## user wants full range for the variable
                varRange <- getFullRange()
            } else {
                if(is(inputRange, 'nodeRangeClass'))
                    varRange <- inputRange$getVarRange() else varRange <- inputRange
            if(numExternalRules) {
                externalRange <- applyGraphIndexRules(varRange, externalRules)
            } else externalRange <- NULL # varRangeClass$new(list(nimbleModel:::indexRange_empty()))
            if(numInternalRules) {
                internalRange <- applyGraphIndexRules(varRange, internalRules)
            } else internalRange <- NULL # varRangeClass$new(list(nimbleModel:::indexRange_empty()))
            result <- nodeRangeClass$new(varName, externalRange, internalRange, index2setID, self)
            return(result)
        },

        getFullRange = function() {
            extent <- lapply(seq_along(allRules$indexRules), function(idx)
                allRules$indexRules[[idx]]$get_max())
            maxes <- rep(0, length(index2setID))
            cnt <- 1
            cntConstant <- 0
            constants <- which(index2setID == 0)
            for(i in seq_along(extent)) {
                if(is(allRules$indexRules[[i]], "indexRuleClass_constant")) {
                    cntConstant <- cntConstant + 1
                    maxes[constants[cntConstant]] <- extent[[i]]
                } else {
                    maxes[index2setID == i] <- extent[[i]] 
                }

            }
            
            return(applyGraphIndexRules(
                    varRangeClass$new(lapply(seq_len(numIndices),
                                             function(i) indexRange(
                                                             substitute(1:MAX, list(MAX = maxes[i]))))),
               allRules))
        },

    )
)

declRuleClass <- R6Class(
    classname = "declRuleClass",
    portable = FALSE,
    inherit = nodeRuleClass,
    public = list(
        stoch = logical(),
        originalIndexRules = NULL, # determines original indexing (based on context)
        
        calculate = NULL,  ## generic function for calculation

        initialize = function(expr, ID, stoch, context = modelContextClass$new(), constants = list()) {
            ## Set up rules that operate on the indexing of the nodes and on
            ## the internal indexing of the elements of a node.
            super$initialize(expr, ID, context = context, constants = constants)
                  
            stoch <<- stoch
            
            originalIndexRules <<- originalIndexRuleClass$new(expr, context, constants)
            calcFun <<- genCalcFun(decl, context)
        },


        genCalcFun = function(decl, context) {
            ## using context$indexVarNames, substitute "idx[1]", "idx[2]", etc.
            ## then generate a function with the decl code in it.
            ## e.g.
            ## function(idx) {
            ##   logProb_y[idx[2]+1, idx[1]] <- dnorm(mu[idx[2]], 1)
            ## }
            ## will need to deal with the various complexities we currently deal with - alt params, truncation, etc.
        }
        
    )
)


## Note: still unclear if calcRules operate on varRanges or nodeRanges (or both)
## to produce calcRanges

calcRuleClass <- R6Class(
    classname = "calcRuleClass",
    portable = FALSE,
    inherit = nodeRuleClass,
    public = list(
        canonicalRange = NULL,
        declRule = NULL,  # multiple calcRules can share a declRule and its density function

        stochParent = FALSE,
        stochDep = FALSE,
        touchedDown = FALSE,
        touchedUp = FALSE,
        parents = numeric(),
        children = numeric(),

        top = FALSE,
        end = FALSE,
        ## latent is !top & !end

        ## should canonicalRange should be in terms of nodes not var?

        ## could calcRule just use declRule internal indexing?
        
        ## This code below needs to operate at the node level since calculation is done by indexing
        ## over nodes.
        ## Actually, indexing is done over original indexes for calculation, so need to think more about this.
        initialize = function(declRule = NULL, expr = NULL, ID, context, constants = list()) {
            ## If LHS is NULL, just use declRule internalRange

            ## This wastes some calculation by redoing the internal/external rule stuff
            ## even though at least the internal stuff already done in the declRule
            if(is.null(expr)) expr <<- declRule$expr
            super$initialize(expr, ID, context = context, constants = constants)

            ## full range, for use with calculate applied to full var

            ## canonicalRule <- makeGraphIndexRules(expr, expr, context, constants)
            canonicalRange <<- applyGraphIndexRules(
                varRangeClass$new(lapply(seq_along(allRules$indexSets$LHSindex2setID),
                    function(i) indexRange(quote(1:Inf)))), allRules)
            context <<- context
            declRule <<- declRule

        },

        ## nodeRuleClass$apply generates a nodeRange
        
        ## Generate calcRange given either a varRange or a nodeRange
        generate_calcRange = function(inputRange) {
            ## Get legitimate nodeRange
            if(!is(inputRange, 'nodeRangeClass')) {
                if(length(inputRange$indexRanges) == 1 && identical(attr(inputRange$indexRanges[[1]], 'rangeType'), "none"))
                    inputRange <- canonicalRange

                nodeRange <- calcRule$apply(inputRange)
            } else nodeRange <- inputRange
            
            indexingRange <- declRule$originalIndexRules$apply(nodeRange$getVarRange())
            if(isEmpty(indexingRange))
                return(NULL)
            result <- calcRangeClass$new(varName, indexingRange, declRule$calcFun, sortID)
            ## if empty, return NULL
            return(result)
        },

        get = function(varRange = NULL, type) {
            ## type is 'end', 'latent', etc.
            ## returns the embedded nodeRange (or subset of it if provided a varRange) that corresponds to 'type'
        },
        
        is_type = function(type) {
            switch(type,
                end = return(end),
                top = return(top),
                latent = return(!end && !top),
                stop("Invalid type ", type)
            )
        },

        set = function(type) {
            switch(type,
                end = end <<- TRUE,
                top = top <<- TRUE,
                stochParent = stochParent <<- TRUE,
                stop("Invalid type ", type)
            )            
        },

        unset = function(type) {
            switch(type,
                end = end <<- FALSE,
                top = top <<- FALSE,
                stochParent = stochParent <<- FALSE,
                stop("Invalid type ", type)
            )
        },

        get_sortID = function() {
            return(declRule$sortID)
        }
    )
)



## build nodefun on the fly when provided a varRange; check if it already exists; pass the fun into the range?
## actually I think it can all be pre-generated

if(FALSE) {
isEmpty <- function(varRange) 
    any(sapply(varRange$indexRanges, function(x) identical(attr(x, 'rangeType'), 'empty')))


calcRule <- calcRuleClass$new(quote(y[i+1]), NULL, context_i)

calcRange <- calcRule$apply(varRangeClass$new(list(indexRange(quote(3:5)))))
expect_equal(calcRange$indexingRange,
                 varRangeClass$new(list(indexRange(quote(2:4)))))

calcRule <- calcRuleClass$new(quote(y[2:4, i+1]), NULL, context_i)

calcRange <- calcRule$apply(varRangeClass$new(list(indexRange(quote(2:4)), indexRange(quote(3:5)))))
expect_equal(calcRange$indexingRange,
                 varRangeClass$new(list(indexRange(quote(2:4)))))

calcRange <- calcRule$apply(varRangeClass$new(list(indexRange(quote(2)), indexRange(quote(3:5)))))
expect_equal(calcRange$indexingRange,
                 varRangeClass$new(list(indexRange(quote(2:4)))))

calcRange <- calcRule$apply(varRangeClass$new(list(indexRange(quote(6)), indexRange(quote(3:5)))))
expect_equal(calcRange, NULL)

calcRange <- calcRule$apply(varRangeClass$new(list(nimbleModel:::indexRange_none())))
expect_equal(calcRange$indexingRange,
                 varRangeClass$new(list(indexRange(quote(1:10)))))
}


## nodeRangeClass

## Holds a collection of like nodes (same declaration, but not (I think) necessarily same graph role or same sort ID).

## example: y[i, 1:5] ~ dmnorm() has:
## externalRange: first index, over selected nodes
## internalRange: 1:5
## e.g., could represent as y[1:3, (1:5)] where () indicates internal grouping

## Convert to subclass of varRangeClass
## need to figure out exactly how indexRanges, internalIndexRanges and externalIndexRanges would be handled/created,
## ideally without redundancy.
nodeRangeClass <- R6Class(
    classname = "nodeRangeClass",
    portable = FALSE,
    public = list(
        varName = NULL,
        externalRange = NULL,  # a varRange
        internalRange = NULL,  # a varRange
        declRule = NULL,
        index2setID = NULL,
        indexID_2_rangeID = NULL,    
        rangeID_2_indexID = NULL,

        initialize = function(varName,
                              externalRange,
                              internalRange,
                              index2setID,
                              declRule) {
            varName <<- varName
            externalRange <<- externalRange
            internalRange <<- internalRange
            declRule <<- declRule  ## pointer to governing declRule
            index2setID <<- index2setID  # should this be a field or just use declRule$index2setID?

            ## These apply to the combination of the externalRange and internalRange;
            ## internalRules indexRanges are considered to be last.
            indexID_2_rangeID <<- index2setID
            indexID_2_rangeID[indexID_2_rangeID != 0] <<- externalRange$indexID_2_rangeID
            indexID_2_rangeID[indexID_2_rangeID == 0] <<- internalRange$indexID_2_rangeID +
                length(externalRange$indexRanges)
            rangeID_2_indexID <<- lapply(seq_len(max(indexID_2_rangeID)),
                                         function(x) which(indexID_2_rangeID == x))

            ## originalIndexRange <<- declRule$originalIndexRules$apply(self$getVarRange())



        },

        getVarRange = function() {
            ## Extract varRange (i.e., ignoring node structure) for use with methods that apply
            ## to varRanges.
            varRangeClass$new(indexInfo = c(externalRange$indexRanges, internalRange$indexRanges),
                              indexOrders = rangeID_2_indexID)
            
        },
        
        expandNames = function() {
            ## Expand externalRange into full matrix (crossed if necessary), keeping full internal
            ## indexing for each individual node.
            ## TODO: Could we instead rely on `varRange2expr`, after extracting the varRange?
            nc <- length(index2setID)  # might be, e.g., 0 1 0 2 3 or 0 1 0 2 1
            str <- paste0(varName, "[")

            nodeInfo <- lapply(externalRange$indexRanges, function(x) {
                if(identical(attr(x, 'rangeType'), 'sequence'))
                    result <- seq(x[[1]][[1]], x[[1]][[2]]) else result <- x[[1]]
                if(!is.matrix(result)) result <- matrix(result, ncol = 1)
                return(result)
            })
            expanded <- do.call(expand.grid, lapply(nodeInfo, function(x) {
                if(is.matrix(x)) 1:nrow(x) else 1:length(x)
            }))

            internalInfo <- lapply(internalRange$indexRanges, function(x) {
                if(identical(attr(x, 'rangeType'), 'sequence')) return(deparse(substitute(X:Y, list(X = x[[1]][[1]], Y = x[[1]][[2]]))))
                return(x)
            })

            ## Mark column position within indexRanges of the externalRange.
            colID <- as.list(rep(1, length(nodeInfo)))
            ## Mark position within internal- and node-related indexes.
            idxInternal <- 1
            idxNode <- 1
            
            for(i in 1:nc) {
                if(i > 1)
                    str <- paste0(str, ", ")
                if(index2setID[i] == 0) {
                    str <- paste0(str, internalInfo[[idxInternal]])
                    idxInternal <- idxInternal + 1
                } else {
                    rangeIdx <-  externalRange$indexID_2_rangeID[idxNode]  ## which indexRange is being used
                    str <- paste0(str, nodeInfo[[rangeIdx]][expanded[ , rangeIdx], colID[[rangeIdx]]])
                    colID[[rangeIdx]] <- colID[[rangeIdx]] + 1  ## index through columns of the indexRange_matrix 
                    idxNode <- idxNode + 1
                }
            }
            str <- paste0(str, "]")
            return(str)
        }
    )
)

nodeRange_isEqual <- function(nr1, nr2) {
    if(is.null(nr1$externalRange) && !is.null(nr2$externalRange) ||
       !is.null(nr1$externalRange) && is.null(nr2$externalRange) ||
       is.null(nr1$internalRange) && !is.null(nr2$internalRange) ||
       !is.null(nr1$internalRange) && is.null(nr2$internalRange))
        return(FALSE)
    ok <- identical(nr1$indexID_2_rangeID, nr2$indexID_2_rangeID) &&
        identical(nr1$rangeID_2_indexID, nr2$rangeID_2_indexID)
    if(!is.null(nr1$externalRange))
        ok <- ok && identical(nr1$externalRange$indexRanges, nr2$externalRange$indexRanges)
    if(!is.null(nr1$internalRange))
        ok <- ok && identical(nr1$internalRange$indexRanges, nr2$internalRange$indexRanges)
    return(ok)
}


## Fracture a LHS rule based on dependencies of another LHS rule, produced from applyGraphIndexRules,
## passed through a nodeRule to produce a nodeRange
## Result can be:
##  - original rule
##  - subset of original rule and a rule created from the fracturingRange
##  - two subsets of original rule and a rule created from the fracturingRange (when dealing with a sequence that is split)

## LHSrule will be a calcRule, not a declRule

fracture <- function(LHSrule, fracturingRange) {
    ## presume fracturingRange is a nodeRange, so has external/internal split consistent with LHS rule
    ## but it could be that we pass in a varRange and then use nodeRule$apply to get the nodeRange
    ## this also means that fracturingRange is the 'intersection' as it shouldn't contain anything not in the LHSrule

    ## A bit convoluted to extract the varRange and then turn that into a nodeRange.
    LHSrange <- LHSrule$apply(LHSrule$getFullRange())
    ## equivalent to LHSrule$apply()

    if(nodeRange_isEqual(LHSrange, fracturingRange)) {
        LHSrule$set('stochParent')
        return(LHSrule)
    }

    ## Indices for internalRange should be identical, so just check/fracture those for external
    identicalIndices <- sapply(seq_along(LHSrange$externalRange$indexID_2_rangeID), function(idx)
        isTRUE(all.equal(LHSrange$externalRange$indexRanges[[LHSrange$externalRange$indexID_2_rangeID[idx]]],
                  fracturingRange$externalRange$indexRanges[[fracturingRange$externalRange$indexID_2_rangeID[[idx]]]])))
    
    nonIdenticalExternalIndices <- which(!identicalIndices)
    nonIdenticalFullIndices <- which(LHSrule$index2setID != 0)[nonIdenticalExternalIndices]
    
    expr <- LHSrule$expr
    singleContexts <- LHSrule$context$singleContexts

    if(LHSrule$numIndices == 1 || length(nonIdenticalFullIndices) == 1) {
        ## Handle simple cases where need only fracture one index
        LHS <- LHSrange$externalRange$indexRanges[[LHSrange$externalRange$indexID_2_rangeID[nonIdenticalExternalIndices]]]
        frac <- fracturingRange$externalRange$indexRanges[[fracturingRange$externalRange$indexID_2_rangeID[nonIdenticalExternalIndices]]]
        typeLHS <- attr(LHS, "rangeType")
        typeFrac <- attr(frac, "rangeType")

        focalContext <- sapply(names(singleContexts), function(nm)
            nm %in% all.vars(expr[[2+nonIdenticalFullIndices]]))

        ## If matrix involved, need to be dealt with so as to create an arbitrary rule.
        if(typeLHS == "matrix" || typeFrac == "matrix") {
            valsLHS <- switch(typeLHS,
                              matrix = LHS[[1]],
                              scalar = LHS[[1]],
                              sequence = LHS[[1]][[1]]:LHS[[1]][[2]],
                              stop("typeLHS not found")
                              )
            valsFrac <- switch(typeFrac,
                              matrix = frac[[1]],
                              scalar = frac[[1]],
                              sequence = frac[[1]][[1]]:frac[[1]][[2]],
                              stop("typeFrac not found")
                              )
            valsLHS <- valsLHS[!valsLHS %in% valsFrac]

            ## Modify LHSrule expr and context to insert vector of relevent values.
            newSingleContexts1 <- singleContexts[!focalContext]
            newSingleContexts2 <- singleContexts[!focalContext]

            newSingleContexts1[[length(newSingleContexts1)+1]] <- modelSingleContext(
                               indexVarExpr = quote(.newidx),
                indexRangeExpr = substitute(1:L, list(L = length(valsLHS))))

            newSingleContexts2[[length(newSingleContexts2)+1]] <- modelSingleContext(
                               indexVarExpr = quote(.newidx),
                indexRangeExpr = substitute(1:L, list(L = length(valsFrac))))

            expr[[nonIdenticalFullIndices+2]] <- quote(.idx[.newidx])
         
            resultRule <- calcRuleClass$new(LHSrule$declRule, expr, context = modelContextClass$new(newSingleContexts1),
                                            constants = list(.idx = valsLHS))

            fracturingRule <- calcRuleClass$new(LHSrule$declRule, expr, context = modelContextClass$new(newSingleContexts2),
                                            constants = list(.idx = valsFrac))
            fracturingRule$set('stochParent')
            
            return(list(fracturingRule, resultRule))
        } else {  # seq+seq or seq+scalar
            if(typeFrac == "scalar")   # process as a sequence
                frac <- indexRange(substitute(A:A, list(A = frac[[1]])))
            if(typeLHS == "scalar") stop("Not expecting LHS to be a scalar")  ## scalar LHS either fully intersected or not intersected
          
            if(frac[[1]][1] == LHS[[1]][[1]] || frac[[1]][[2]] == LHS[[1]][[2]]) {
                ## Shrink existing sequence
                if(frac[[1]][[1]] == LHS[[1]][[1]]) 
                    LHS[[1]][[1]] <- frac[[1]][[2]]+1 else LHS[[1]][[2]] <- frac[[1]][[1]]-1

                newSingleContexts1 <- singleContexts[!focalContext]
                newSingleContexts2 <- singleContexts[!focalContext]

                newSingleContexts1[[length(newSingleContexts1)+1]] <- modelSingleContext(
                    indexVarExpr = quote(.newidx),
                    indexRangeExpr = substitute(A:B, list(A = LHS[[1]][[1]], B = LHS[[1]][[2]])))

                newSingleContexts2[[length(newSingleContexts2)+1]] <- modelSingleContext(
                    indexVarExpr = quote(.newidx),
                    indexRangeExpr = substitute(A:B, list(A = frac[[1]][[1]], B = frac[[1]][[2]])))

                expr[[nonIdenticalFullIndices+2]] <- newSingleContexts1[[length(newSingleContexts1)]]$indexVarExpr

                resultRule <- calcRuleClass$new(LHSrule$declRule, expr, context = modelContextClass$new(newSingleContexts1))

                fracturingRule <- calcRuleClass$new(LHSrule$declRule, expr, context = modelContextClass$new(newSingleContexts2))
                fracturingRule$set('stochParent')
                
                return(list(fracturingRule, resultRule))
            } else {
                ## Split an existing sequence 
                newSingleContexts1 <- singleContexts[!focalContext]
                newSingleContexts2 <- singleContexts[!focalContext]
                newSingleContexts3 <- singleContexts[!focalContext]

                expr1 <- expr2 <- expr3 <- expr
                newSingleContexts1[[length(newSingleContexts1)+1]] <- modelSingleContext(
                    indexVarExpr = quote(.newidx),
                    indexRangeExpr = substitute(A:B, list(A = LHS[[1]][[1]], B = frac[[1]][[1]]-1)))
                expr1[[nonIdenticalFullIndices+2]] <- newSingleContexts1[[length(newSingleContexts1)]]$indexVarExpr

                newSingleContexts2[[length(newSingleContexts2)+1]] <- modelSingleContext(
                    indexVarExpr = quote(.newidx),
                    indexRangeExpr = substitute(A:B, list(A = frac[[1]][[2]]+1, B = LHS[[1]][[2]])))
                expr2[[nonIdenticalFullIndices+2]] <- newSingleContexts2[[length(newSingleContexts2)]]$indexVarExpr

                newSingleContexts3[[length(newSingleContexts3)+1]] <- modelSingleContext(
                    indexVarExpr = quote(.newidx),
                    indexRangeExpr = substitute(A:B, list(A = frac[[1]][[1]], B = frac[[1]][[2]])))
                expr3[[nonIdenticalFullIndices+2]] <- newSingleContexts3[[length(newSingleContexts3)]]$indexVarExpr
               
                resultRule1 <- calcRuleClass$new(LHSrule$declRule, expr1, context = modelContextClass$new(newSingleContexts1))
                resultRule2 <- calcRuleClass$new(LHSrule$declRule, expr2, context = modelContextClass$new(newSingleContexts2))
                fracturingRule <- calcRuleClass$new(LHSrule$declRule, expr3, context = modelContextClass$new(newSingleContexts3))
                fracturingRule$set('stochParent')
                
                return(list(fracturingRule, resultRule1, resultRule2))
            }
        }
    } else {     ## unroll, exclude, create new arbitrary rule based on all non-identical indices
        unrolledLHS <- LHSrange$externalRange$getIndexRangeMatrix(nonIdenticalExternalIndices)
        unrolledFrac <- fracturingRange$externalRange$getIndexRangeMatrix(nonIdenticalExternalIndices)

        lhsAsChar <- do.call(paste, as.data.frame(unrolledLHS[[1]]))
        fracAsChar <- do.call(paste, as.data.frame(unrolledFrac[[1]]))

        remaining <- !lhsAsChar %in% fracAsChar
        mat1 <- unrolledLHS[[1]][remaining, ]
        mat2 <- unrolledLHS[[1]][!remaining, ]

        focalContext <- sapply(names(singleContexts), function(nm)
            nm %in% unlist(lapply(2+nonIdenticalFullIndices, function(x) all.vars(expr[[x]]))))

        if(sum(!focalContext)) {
            newSingleContexts1 <- singleContexts[!focalContext]
            newSingleContexts2 <- singleContexts[!focalContext]
        } else newSingleContexts1 <- newSingleContexts2 <- list()

        newSingleContexts1[[length(newSingleContexts1) + 1]] <- modelSingleContext(
                               indexVarExpr = quote(.newidx),
            indexRangeExpr = substitute(1:L, list(L = nrow(mat1))))

        newSingleContexts2[[length(newSingleContexts2) + 1]] <- modelSingleContext(
                               indexVarExpr = quote(.newidx),
            indexRangeExpr = substitute(1:L, list(L = nrow(mat2))))

        nms <- paste0(".idx", seq_len(ncol(mat1)), "[.newidx]")
        for(i in seq_along(nonIdenticalFullIndices)) 
            expr[[nonIdenticalFullIndices[i]+2]] <- parse(text = nms[i])[[1]]
        
        constants1 <- lapply(seq_len(ncol(mat1)), function(i) mat1[,i])
        names(constants1) <- paste0(".idx", seq_along(constants1))
        constants2 <- lapply(seq_len(ncol(mat2)), function(i) mat2[,i])
        names(constants2) <- paste0(".idx", seq_along(constants2))

      
        resultRule <- calcRuleClass$new(LHSrule$declRule, expr, context = modelContextClass$new(newSingleContexts1),
                                        constants = constants1)
        fracturingRule <- calcRuleClass$new(LHSrule$declRule, expr, context = modelContextClass$new(newSingleContexts2),
                                        constants = constants2)
        fracturingRule$set('stochParent')

        return(list(fracturingRule, resultRule))
    }
}

## I think nodeRuleClass can stay as a generic nodeRule rather than needed to be a calcRule,
## even though in real work, input would be a calcRule.

if(FALSE) {  
    ## Hopefully comprehensive testing of exclude(); move into test-nodeRules.R or test-fracture.R
    library(nimbleModel)
    library(testthat)
   singleContext1 <-
       modelSingleContext(forCode = quote(for(i in 2:8){}))
   
   singleContext2 <-
       modelSingleContext(forCode = quote(for(j in 1:4){}))
   
   context_0 <- modelContextClass$new()
   context_i <- modelContextClass$new(list(singleContext1))
   context_j <- modelContextClass$new(list(singleContext2))
   
   context_ij <- modelContextClass$new(list(singleContext1,
                                            singleContext2))
   
   ## scalar overlap at end
   LHS <- quote(mu[i+1])
   LHSrule <- nodeRuleClass$new(LHS, 1, context_i)
   ## fracture with mu[3]
   fracRange <- LHSrule$apply(varRangeClass$new(list(indexRange(3))))
   
   result <- fracture(LHSrule, fracRange)

   expect_identical(length(result), 2L)
   expr <- quote(mu[i])
   context_tmp <- modelContextClass$new(list(modelSingleContext(forCode = quote(for(i in 4:9){}))))
   expected <- nodeRuleClass$new(expr, 1, context_tmp)
   expect_identical(result[[1]]$externalRules$indexRules[[1]]$setupResults,
                    expected$externalRules$indexRules[[1]]$setupResults)
   context_tmp <- modelContextClass$new(list(modelSingleContext(forCode = quote(for(i in 3:3){}))))
   expected <- nodeRuleClass$new(expr, 1, context_tmp)
   expect_identical(result[[2]]$externalRules$indexRules[[1]]$setupResults,
                    expected$externalRules$indexRules[[1]]$setupResults)

   ## seq overlap at end
   LHS <- quote(mu[i+1])
   LHSrule <- nodeRuleClass$new(LHS, 1, context_i)
   ## fracture with mu[3:4]
   fracRange <- LHSrule$apply(varRangeClass$new(list(indexRange(quote(3:4)))))
   
   result <- fracture(LHSrule, fracRange)

   expect_identical(length(result), 2L)
   expr <- quote(mu[i])
   context_tmp <- modelContextClass$new(list(modelSingleContext(forCode = quote(for(i in 5:9){}))))
   expected <- nodeRuleClass$new(expr, 1, context_tmp)
   expect_identical(result[[1]]$externalRules$indexRules[[1]]$setupResults,
                    expected$externalRules$indexRules[[1]]$setupResults)
   context_tmp <- modelContextClass$new(list(modelSingleContext(forCode = quote(for(i in 3:4){}))))
   expected <- nodeRuleClass$new(expr, 1, context_tmp)
   expect_identical(result[[2]]$externalRules$indexRules[[1]]$setupResults,
                    expected$externalRules$indexRules[[1]]$setupResults)
      
   ## seq overlap in middle
   LHS <- quote(mu[i+1])
   LHSrule <- nodeRuleClass$new(LHS, 1, context_i)
   ## fracture with mu[4:5]
   fracRange <- LHSrule$apply(varRangeClass$new(list(indexRange(quote(4:5)))))
   
   result <- fracture(LHSrule, fracRange)

   expect_identical(length(result), 3L)
   expr <- quote(mu[i])
   context_tmp <- modelContextClass$new(list(modelSingleContext(forCode = quote(for(i in 3:3){}))))
   expected <- nodeRuleClass$new(expr, 1, context_tmp)
   expect_identical(result[[1]]$externalRules$indexRules[[1]]$setupResults,
                    expected$externalRules$indexRules[[1]]$setupResults)
   context_tmp <- modelContextClass$new(list(modelSingleContext(forCode = quote(for(i in 6:9){}))))
   expected <- nodeRuleClass$new(expr, 1, context_tmp)
   expect_identical(result[[2]]$externalRules$indexRules[[1]]$setupResults,
                    expected$externalRules$indexRules[[1]]$setupResults)
   context_tmp <- modelContextClass$new(list(modelSingleContext(forCode = quote(for(i in 4:5){}))))
   expected <- nodeRuleClass$new(expr, 1, context_tmp)
   expect_identical(result[[3]]$externalRules$indexRules[[1]]$setupResults,
                    expected$externalRules$indexRules[[1]]$setupResults)
      

   ## seq and matrix
   LHS <- quote(mu[i+1])
   LHSrule <- nodeRuleClass$new(LHS, 1, context_i)
   ## fracture with matrix
   idx <- c(3,6,9)
   fracRange <- LHSrule$apply(varRangeClass$new(list(indexRange(matrix(idx)))))
   
   result <- fracture(LHSrule, fracRange)

   expect_identical(length(result), 2L)
   expr <- quote(mu[idx[i]])
   idx2 <- c(4,5,7,8)
   context_tmp <- modelContextClass$new(list(modelSingleContext(forCode = quote(for(i in 1:4){}))))
   expected <- nodeRuleClass$new(expr, 1, context_tmp, constants = list(idx = idx2))
   expect_equal(result[[1]]$externalRules$indexRules[[1]]$setupResults,
                    expected$externalRules$indexRules[[1]]$setupResults)
   context_tmp <- modelContextClass$new(list(modelSingleContext(forCode = quote(for(i in 1:3){}))))
   expected <- nodeRuleClass$new(expr, 1, context_tmp, constants = list(idx = idx))
   expect_equal(result[[2]]$externalRules$indexRules[[1]]$setupResults,
                expected$externalRules$indexRules[[1]]$setupResults)

   ## basic case with one external, one internal: mu[1:3, i]
   LHS <- quote(mu[1:3,i])
   LHSrule <- nodeRuleClass$new(LHS, 1, context_i)
   fracRange <- LHSrule$apply(varRangeClass$new(list(indexRange(quote(1:3)),
                                                     indexRange(quote(2:3)))))
   
   result <- fracture(LHSrule, fracRange)

   expect_identical(length(result), 2L)
   expect_identical(result[[1]]$internalRules$indexRules[[1]]$setupResults,
                LHSrule$internalRules$indexRules[[1]]$setupResults)
   expect_identical(result[[2]]$internalRules$indexRules[[1]]$setupResults,
                    LHSrule$internalRules$indexRules[[1]]$setupResults)
   context_tmp <- modelContextClass$new(list(modelSingleContext(forCode = quote(for(i in 4:8){}))))
   expected <- nodeRuleClass$new(LHS, 1, context_tmp)
   expect_identical(result[[1]]$externalRules$indexRules[[1]]$setupResults,
                    expected$externalRules$indexRules[[1]]$setupResults)
   context_tmp <- modelContextClass$new(list(modelSingleContext(forCode = quote(for(i in 2:3){}))))
   expected <- nodeRuleClass$new(LHS, 1, context_tmp)
   expect_identical(result[[2]]$externalRules$indexRules[[1]]$setupResults,
                    expected$externalRules$indexRules[[1]]$setupResults)

   ## two external indices, one fractured, two constant internal rules
   LHS <- quote(mu[1:3,j,i,2:3])
   LHSrule <- nodeRuleClass$new(LHS, 1, context_ij)
   fracRange <- LHSrule$apply(varRangeClass$new(list(indexRange(quote(1:3)),
                                                     indexRange(quote(1:4)),
                                                     indexRange(matrix(c(2,4))),
                                                     indexRange(2))))
   
   result <- fracture(LHSrule, fracRange)
  
   expect_identical(length(result), 2L)
   expect_identical(LHSrule$index2setID, c(0,2,1,0))
   for(k in 1:2) {
       for(kk in 1:2)
           expect_identical(result[[k]]$internalRules$indexRules[[kk]]$setupResults,
                            LHSrule$internalRules$indexRules[[kk]]$setupResults)
       expect_identical(result[[k]]$externalRules$indexRules[[1]]$setupResults,
                        LHSrule$externalRules$indexRules[[2]]$setupResults)
       expect_identical(result[[k]]$index2setID, c(0,1,2,0))
   }
   context_tmp <- modelContextClass$new(list(modelSingleContext(forCode = quote(for(i in 1:5){}))))
   idx <- as.integer(c(3,5,6,7,8))
   expr <- quote(mu[idx[i]])
   expected <- nodeRuleClass$new(expr, FALSE, 1, FALSE, context_tmp, constants = list(idx = idx))
   expect_equal(result[[1]]$externalRules$indexRules[[2]]$setupResults,
                        expected$externalRules$indexRules[[1]]$setupResults)
   context_tmp <- modelContextClass$new(list(modelSingleContext(forCode = quote(for(i in 1:2){}))))
   idx <- as.integer(c(2,4))
   expr <- quote(mu[idx[i]])
   expected <- nodeRuleClass$new(expr, FALSE, 1, FALSE, context_tmp, constants = list(idx = idx))
   expect_equal(result[[2]]$externalRules$indexRules[[2]]$setupResults,
                        expected$externalRules$indexRules[[1]]$setupResults)

   ## two external indices, one fractured, one constant internal rule and additional external from scalar
   LHS <- quote(mu[1:3,j,i,2])
   LHSrule <- nodeRuleClass$new(LHS, 1, context_ij)
   fracRange <- LHSrule$apply(varRangeClass$new(list(indexRange(quote(1:3)),
                                                     indexRange(quote(1:4)),
                                                     indexRange(matrix(c(2,4))),
                                                     indexRange(2))))
   
   result <- fracture(LHSrule, fracRange)

   ## Just check stuff related to the scalar constant index, given similarity to above test.
   expect_identical(length(result), 2L)
   expect_identical(LHSrule$index2setID, c(0,2,1,0))
   for(k in 1:2) {
       expect_identical(result[[k]]$internalRules$indexRules[[1]]$setupResults,
                        LHSrule$internalRules$indexRules[[1]]$setupResults)
       expect_identical(result[[k]]$externalRules$indexRules[[1]]$setupResults,
                        LHSrule$externalRules$indexRules[[2]]$setupResults)
       expect_identical(result[[k]]$index2setID, c(0,1,2,0))
   }

   
   ## two external indices, both fractured: mu[1:3, j ,2, i]
   LHS <- quote(mu[1:3,j,i,2])
   LHSrule <- nodeRuleClass$new(LHS, 1, context_ij)
   fracRange <- LHSrule$apply(varRangeClass$new(list(indexRange(quote(1:3)),
                                                     indexRange(quote(2:3)),
                                                     indexRange(quote(2:3)),
                                                     indexRange(2))))
   
   result <- fracture(LHSrule, fracRange)

   expect_identical(length(result), 2L)
   expect_identical(LHSrule$index2setID, c(0,2,1,0))
   for(k in 1:2) {
       expect_identical(result[[k]]$internalRules$indexRules[[1]]$setupResults,
                        LHSrule$internalRules$indexRules[[1]]$setupResults)
       expect_identical(result[[k]]$index2setID, c(0,1,1,0))
   }

   context_tmp <- modelContextClass$new(list(modelSingleContext(forCode = quote(for(i in 1:24){}))))
   idx1 <- as.integer(c(1,4,1,4,rep(1:4, 5)))
   idx2 <- as.integer(c(2,2,3,3,rep(4:8, each = 4)))
   expr <- quote(mu[idx1[i],idx2[i]])
   expected <- nodeRuleClass$new(expr, FALSE, 1, FALSE, context_tmp, constants = list(idx1 = idx1, idx2 = idx2))
   expect_equal(result[[1]]$externalRules$indexRules[[1]]$setupResults,
                expected$externalRules$indexRules[[1]]$setupResults)
   context_tmp <- modelContextClass$new(list(modelSingleContext(forCode = quote(for(i in 1:4){}))))
   idx1 <- as.integer(c(2,3,2,3))
   idx2 <- as.integer(c(2,2,3,3))
   expr <- quote(mu[idx1[i],idx2[i]])
   expected <- nodeRuleClass$new(expr, FALSE, 1, FALSE, context_tmp, constants = list(idx1 = idx1, idx2 = idx2))
   expect_equal(result[[2]]$externalRules$indexRules[[1]]$setupResults,
                expected$externalRules$indexRules[[1]]$setupResults)


   ## two external indices fractured: mu[1:3, j ,2, i] , based on 2-d matrix
   LHS <- quote(mu[1:3,j,i,2])
   LHSrule <- nodeRuleClass$new(LHS, 1, context_ij)
    
   fracRange <- LHSrule$apply(varRangeClass$new(list(indexRange(quote(1:3)),
                                                     indexRange(matrix(c(2,3,3,7), ncol = 2)),
                                                     indexRange(2))))

   result <- fracture(LHSrule, fracRange)

   expect_identical(length(result), 2L)
   expect_identical(LHSrule$index2setID, c(0,2,1,0))
   for(k in 1:2) {
       expect_identical(result[[k]]$internalRules$indexRules[[1]]$setupResults,
                        LHSrule$internalRules$indexRules[[1]]$setupResults)
       expect_identical(result[[k]]$index2setID, c(0,1,1,0))
   }

   context_tmp <- modelContextClass$new(list(modelSingleContext(forCode = quote(for(i in 1:26){}))))
   idx1 <- as.integer(rep(1:4, 7))
   idx2 <- as.integer(rep(2:8, each = 4))
   wh <- (idx1 == 2 & idx2 == 3) | (idx1 == 3 & idx2 == 7)
   idx1 <- idx1[!wh]
   idx2 <- idx2[!wh]
   expr <- quote(mu[idx1[i],idx2[i]])
   expected <- nodeRuleClass$new(expr, FALSE, 1, FALSE, context_tmp, constants = list(idx1 = idx1, idx2 = idx2))
   expect_equal(result[[1]]$externalRules$indexRules[[1]]$setupResults,
                expected$externalRules$indexRules[[1]]$setupResults)
   context_tmp <- modelContextClass$new(list(modelSingleContext(forCode = quote(for(i in 1:2){}))))
   idx1 <- as.integer(c(2,3))
   idx2 <- as.integer(c(3,7))
   expr <- quote(mu[idx1[i],idx2[i]])
   expected <- nodeRuleClass$new(expr, FALSE, 1, FALSE, context_tmp, constants = list(idx1 = idx1, idx2 = idx2))
   expect_equal(result[[2]]$externalRules$indexRules[[1]]$setupResults,
                expected$externalRules$indexRules[[1]]$setupResults)

   
}

