# The nodeRuleClass is the base class for declRuleClass, calcRuleClass, and rhsRuleClass.
# These classes represent the indexing of one or more nodes in a model,
# distinguishing indexing across nodes (external indexing) from indexing
# within a node (internal indexing).

# Unlike a graphRule, a nodeRule does not translate indexing between variables;
# rather it simply represents the valid index values for a variable.

# There is one declRule for each declaration in a model, representing the indexing for the LHS variable.

# calcRules are generated by starting with declRules and then fracturing (with `fracture`)
# based on top-down processing. This produces a calcRule for each set of nodes
# from a declaration that can be calculated together (same sortID)
# (as well as the special case of state-space model type formulations).

# Base class for all node-related classes
nodeRuleClass <- R6Class(
  classname = "nodeRuleClass",
  portable = FALSE,
  public = list(
    context = NULL,
    expr = NULL,
    ID = character(), # need to look up calcRules by name not position
    varName = character(),
    fullRule = NULL,
    # `externalRule` and `internalRule` are subsets of the fullRule,
    # so sets of indexRules and associated information.
    externalRule = list(), # indexing for the nodes
    internalRule = list(), # indexing for components of multivariate nodes
    numExternalIndexRules = 0,
    numInternalIndexRules = 0,
    indexSlotToSet = NULL,
    fullRange = list(),
    initialize = function(expr, ID, context = modelContextClass$new(), constants = list(), isRHS = FALSE) {
      varName <<- getVarName(expr)
      ID <<- as.character(ID)
      context <<- context
      expr <<- expr

      # Note: this is awkward to go into the data structures and modify them

      # We'll use graphRules, though only have a single side of declaration.
      fullRule <<- graphRuleClass$new(expr, expr, context, constants, checkVars = !isRHS)
      indexSlotToSet <<- fullRule$indexSets$toIndexSlotToSet

      fullRange <<- fullRule$apply(varName)

      if (length(fullRule$indexRules)) { # if any indexing
        isConstant <- sapply(fullRule$indexRules, function(x) inherits(x, "indexRuleConstantClass"))

        # Treat constants as internal rules that don't relate to indexing over nodes.
        # Need to relate constant rule types to indexing; constant rules are in order of constant indices.
        constantIndices <- fullRule$indexSets$toIndexSlotToSet == 0

        externalRule <<- fullRule$clone()
        externalRule$indexRules[isConstant] <<- NULL
        externalRule$indexSets$toIndexSlotToSet <<-
          externalRule$indexSets$toIndexSlotToSet[!constantIndices]

        internalRule <<- fullRule$clone()
        internalRule$indexRules[!isConstant] <<- NULL

        # Transform indexSets as if LHS is just from the constant rules and RHS is
        # all constants. E.g., `y[1] <- y[1,1]` if one of two slots is constant.
        toExpr <- parse(text = paste0("y[", paste(rep(1, sum(constantIndices)), collapse = ","), "]"))[[1]]
        fromExpr <- parse(text = paste0("y[", paste(rep(1, length(constantIndices)), collapse = ","), "]"))[[1]]
        internalRule$indexSets <- makeSeparableIndexSets(toExpr, fromExpr, modelContextClass$new())

        numExternalIndexRules <<- length(externalRule$indexRules)
        numInternalIndexRules <<- length(internalRule$indexRules)
      }
    },

    # Generate nodeRange from a varRange, nodeRange, or char representation of a varRange (e.g., 'y[1:3]'.
    # By default returns the full range of the rule.
    apply = function(varRange = NULL) {
      if (is.null(varRange)) {
        varRange <- varName
      }
      name <- getVarName(varRange)
      if (name != varName) { # variable names don't match
        return(NULL)
      }
      if (is.character(varRange)) {
        if (name == varRange) {
          varRange <- fullRule$getFromRange() # e.g., 'y' -- produce full range of the rule
        } else {
          varRange <- varRangeClass$new(varRange)
        }
      } # e.g., 'y[1:3]'

      if (!(numExternalIndexRules + numInternalIndexRules) &&
        !varRange$isNone()) {
        stop("incorrect number of input indices in `", varRange$toChar(), "`")
      }

      # Apply both the external and internal indexRules.
      if (numExternalIndexRules) {
        externalRange <- externalRule$apply(varRange)
        if (is.null(externalRange)) {
          return(NULL)
        }
      } else {
        externalRange <- varRangeClass$new(list())
      }
      if (numInternalIndexRules) {
        internalRange <- internalRule$apply(varRange)
        if (is.null(internalRange)) {
          return(NULL)
        }
      } else {
        internalRange <- varRangeClass$new(list())
      }

      decl <- NULL
      if (inherits(self, "declRuleClass")) decl <- self$decl
      if (inherits(self, "calcRuleClass")) decl <- self$declRule$decl

      return(
        nodeRangeClass$new(
          varName, externalRange, internalRange,
          indexSlotToSet, decl
        )
      )
    }
  )
)

# Class for representing nodes at the declaration level.
declRuleClass <- R6Class(
  classname = "declRuleClass",
  portable = FALSE,
  inherit = nodeRuleClass,
  public = list(
    originalIndexingRule = NULL, # Determines original indexing (based on context).
    decl = NULL, # Full declInfo; nodeRuleClass$expr is just LHS.
    initialize = function(decl, ID, context = modelContextClass$new(), constants = list()) {
      decl <<- decl
      super$initialize(decl$code[[2]], ID, context = context, constants = constants)

      # `expr` in is parent class.
      originalIndexingRule <<- originalIndexingRuleClass$new(expr, context, constants)
    }
  )
)

# Class for representing sets of nodes from a single declaration that
# can be calculated together (same `sortID`).
# Also used for representing states in a state-space case where calculation
# needs to be done in order.
calcRuleClass <- R6Class(
  classname = "calcRuleClass",
  portable = FALSE,
  inherit = nodeRuleClass,
  public = list(
    canonicalRange = NULL,
    declRule = NULL, # for access to nodeFunctions, since multiple calcRules can share a declRule

    stochParent = NA,
    stochDep = NA,
    parents = numeric(),
    children = numeric(),
    top = FALSE,
    end = NA,

    # `Inf` is placeholder for 'unresolved' (`NULL` causes processing issues)
    sortID = Inf,
    multiSortIDindex = NULL,
    initialize = function(declRule = NULL, expr = NULL, ID, context, constants = list()) {
      # If LHS is NULL, just use declRule internalRange

      # This wastes some calculation by redoing the internal/external rule stuff
      # even though at least the internal stuff already done in the declRule
      if (is.null(expr)) expr <- declRule$expr
      super$initialize(expr, ID, context = context, constants = constants)

      # Full range, for use with calculate applied to full variable.
      canonicalRange <<- declRule$fullRange
      declRule <<- declRule
    },

    # Create calcRange given a varRange (possibly a nodeRange).
    # (calcRuleClass$apply generates a nodeRange (inheriting from nodeRuleClass$apply().)
    makeCalcRange = function(inputRange = NULL) {
      if (is.null(inputRange)) {
        return(NULL)
      }
      # if(is.null(inputRange))
      #     inputRange <- canonicalRange  # TODO: where/how handle this case?
      if (!is.null(inputRange$varName) && !is.null(varName) && inputRange$varName != varName) {
        stop("`inputRange` variable name does not match the `calcRule` variable name.")
      }

      # Need original indexing because nodeFunctions will use that indexing
      # (e.g. `y[i+1]` needs value of `i`).
      indexingRange <- declRule$originalIndexingRule$apply(inputRange)
      if (is.null(indexingRange)) {
        return(NULL)
      }
      if(length(sortID) > 1)
        newSortID <- sortID[inputRange$indexRanges[[multiSortIDindex]]$getValuesAsMatrix()] else newSortID = sortID
      result <- calcRangeClass$new(varName, indexingRange, as.numeric(declRule$ID), newSortID, multiSortIDindex, self)
      return(result)
    },
    makeCalcRangeScalars = function(calcRange) {
      # should take a calcRange
      if (!inherits(calcRange, 'calcRangeClass'))
        stop("input to `makeCalcRangeScalars` must be a `calcRange`")
      if (!is.null(calcRange$varName) && !is.null(varName) && calcRange$varName != varName) {
        stop("`calcRange` variable name does not match the `calcRule` variable name.")
      }

      # Need original indexing because nodeFunctions will use that indexing
      # (e.g. `y[i+1]` needs value of `i`).
      if(length(calcRange$multiSortIDindex) != 1)
        stop("attempting to split calcRange that have multiple indexing")
      indices <- c(calcRange$indexingRange$indexRanges[[calcRange$multiSortIDindex]]$getValuesAsMatrix())
      sortIDs <- calcRange$sortID[!is.na(calcRange$sortID)]
      if(length(indices) != length(sortIDs))
        stop("mismatch between indexing values and node-based sortIDs")
      results <- lapply(seq_along(indices), \(i)
                        calcRangeClass$new(varName, varRangeClass$new(list(indexRangeMatrixClass$new(matrix(indices[i]), sort=FALSE))),
                                as.numeric(declRule$ID), sortIDs[i], multiSortIDindex, self))
      return(results)
    },    
    isOfType = function(type) {
      switch(type,
        end = return(end),
        top = return(top),
        latent = return(!end && !top),
        stop("invalid type, `", type, "`.")
      )
    },
    set = function(type) {
      switch(type,
        end = end <<- TRUE,
        top = top <<- TRUE,
        stochParent = stochParent <<- TRUE,
        stochDep = stochDep <<- TRUE,
        stop("invalid type, `", type, "`.")
      )
      return(TRUE)
    },
    unset = function(type) {
      switch(type,
        end = end <<- FALSE,
        top = top <<- FALSE,
        stochParent = stochParent <<- FALSE,
        stochDep = stochDep <<- FALSE,
        stop("invalid type, `", type, "`.")
      )
      return(FALSE)
    },

    # Check for only constants on RHS, in which case this is a top rule.
    checkAllRHSconstants = function(constants) {
      vars <- all.vars(declRule$decl$code[[3]])
      if (all(vars %in% c(names(constants), declRule$context$indexVarNames))) {
        return(TRUE)
      } else {
        return(FALSE)
      }
    },
    setParents = function(IDs) {
      parents <<- c(parents, IDs[!IDs %in% parents])
    },
    setChildren = function(IDs) {
      children <<- c(children, IDs[!IDs %in% children])
    },
    unsetParents = function(IDs) {
      parents <<- parents[!parents %in% IDs]
    },
    unsetChildren = function(IDs) {
      children <<- children[!children %in% IDs]
    },

    # Used recursively to determine if a rule has stochastic dependents.
    # Terminates if no children or if stochastic dependent found.
    setStochDep = function(calcRules, alreadySeen = character(0)) {
      if (!is.na(stochDep)) {
        return(stochDep)
      }
      if (!length(children)) {
        return(unset("stochDep"))
      }
      toCheck <- children[!children %in% alreadySeen]  # Avoid infinite recursion in cylic cases.
      # First check if any children are stochastic.
      stoch <- sapply(toCheck, function(idx) {
        calcRules[[idx]]$declRule$decl$stoch
      })
      if (any(stoch)) {
        return(set("stochDep"))
      } else { # Check if children (all deterministic) have stoch dependents.
        idx <- 1
        while (idx <= length(stoch)) {
          # Walk down the tree as needed, avoiding infinitely looping over calcRule itself.
          # Can stop when find first stochastic dependent.
          if (toCheck[idx] != ID && calcRules[[toCheck[idx]]]$setStochDep(calcRules, c(alreadySeen, toCheck))) {
            return(set("stochDep"))
          }
          idx <- idx + 1
        }
      }
      return(unset("stochDep"))
    },

    # Used recursively to determine if a rule has stochastic parents.
    # Terminates if no parents or if stochastic parent found.
    setStochParent = function(calcRules, alreadySeen = character(0)) {
      if (!is.na(stochParent)) {
        return(stochParent)
      }
      if (!length(parents)) {
        return(unset("stochParent"))
      }
      toCheck <- parents[!parents %in% alreadySeen]  # Avoid infinite recursion in cylic cases.
      # First check if any parents are stochastic.
      stoch <- sapply(toCheck, function(idx) {
        calcRules[[idx]]$declRule$decl$stoch
      })
      if (any(stoch)) {
        return(set("stochParent"))
      } else { # Check if parents (all deterministic) have stoch parents.
        idx <- 1
        while (idx <= length(stoch)) {
          # Walk up the tree as needed, avoiding infinitely looping over calcRule itself.
          # Can stop when find first stochastic parent.
          if (toCheck[idx] != ID && calcRules[[toCheck[idx]]]$setStochParent(calcRules, c(alreadySeen, toCheck))) {
            return(set("stochParent"))
          }
          idx <- idx + 1
        }
      }
      return(unset("stochParent"))
    },

    # Determine sortID recursively.
    # sortID gives ordering in which calculations need to be done.
    # Use bottom-up determination (since want maximal ties amongst potentially most-numerous data nodes).
    # Easiest here to have bottom-most rules have sortID of 1, since we have to start with bottom.
    setSortID = function(calcRules, ancestors = NULL) {
      if (length(sortID) == 1 && is.infinite(sortID)) {
        if (!length(children)) {
          sortID <<- 1
          return(sortID)
        }
        # Set NAs for graph cycles (SSM type cases), which will be handled elsewhere.
        if (any(children %in% ancestors)) {
          # warning("Cycle found in model graph. NIMBLE does not allow cyclic models.")
          sortID <<- as.numeric(NA)
          # This allows NA to propagate into other nodes involved in cycle.
          sapply(children, function(i) {
            calcRules[[i]]$setSortID(calcRules, c(ancestors, ID))
          })
          return(sortID)
        }
        # sortID is next largest integer above the maximum sortIDs of the children.
        result <- max(sapply(children, function(i) {
          calcRules[[i]]$setSortID(calcRules, c(ancestors, ID))
        })) + 1
        # Avoid propagating NA upwards, leave those further up as Inf (i.e., 'unresolved').
        if (!is.na(result)) {
          sortID <<- result
        }
      }
      if (length(sortID) == 1 && is.na(sortID)) {
        return(NA)
      } else {
        return(max(sortID, na.rm = TRUE))
      } # max() accounts for SSM case where have multiple sortIDs
    }
  )
)

# calcRanges manage the calculation information for one or more nodes, handling the indexing
calcRangeClass <- R6Class(
  classname = "calcRangeClass",
  portable = FALSE,
  public = list(
    varName = NULL,
    indexingRange = NULL,
    sortID = NULL,
    multiSortIDindex = NULL,
    declID = NULL,
    calcRule = NULL,
    initialize = function(varName, indexingRange, declID, sortID, multiSortIDindex, calcRule) {
      varName <<- varName
      indexingRange <<- indexingRange
      sortID <<- sortID
      declID <<- declID
      multiSortIDindex <<- multiSortIDindex
      calcRule <<- calcRule
    }
  )
)


# Class for managing a set of like nodes (same declaration, but not necessarily same graph role or same sort ID).
# Basically a `varRange` but with indication of which indexRanges relate to node indexing (external indexRanges)
# (versus internal indexing of elements within a multivariate node) and a pointer to the declRule governing the nodes.

# example: y[i, 1:5] ~ dmnorm() has:
# externalRange: first index, over selected nodes
# internalRange: 1:5

nodeRangeClass <- R6Class(
  classname = "nodeRangeClass",
  portable = FALSE,
  inherit = varRangeClass,
  public = list(
    decl = NULL,
    boolExternalIndexRanges = NULL,
    numExternalIndexRanges = NULL,
    nodeChars = NULL,
    initialize = function(varName,
                          externalRange,
                          internalRange,
                          indexSlotToSet,
                          decl) {
      # Convert scalar external indexRanges to internal.
      if (length(externalRange$indexRanges)) {
        scalars <- sapply(
          externalRange$indexRanges,
          function(x) inherits(x, "indexRangeScalarClass")
        )
        if (sum(scalars)) {
          internalRange$indexRanges <- c(internalRange$indexRanges, externalRange$indexRanges[scalars])
          externalRange$indexRanges <- externalRange$indexRanges[!scalars]
          externalRange$indexSlotToRange <- externalRange$indexSlotToRange[!externalRange$indexSlotToRange %in% which(scalars)]
          for (i in seq_along(externalRange$indexSlotToRange))
            externalRange$indexSlotToRange[i] <- externalRange$indexSlotToRange[i] -
              sum(externalRange$indexSlotToRange[i] > which(scalars))
          # for (idx in which(scalars)) {
          #   externalRange$indexSlotToRange[externalRange$indexSlotToRange > idx] <-
          #    externalRange$indexSlotToRange[externalRange$indexSlotToRange > idx] - 1
          # }
          indexSlotToSet[indexSlotToSet != 0][unlist(externalRange$rangeToIndexSlot[scalars])] <- -1
        }
      } else {
        scalars <- logical(0)
      }

      # CHECK: could consider converting 1-row indexRangeMatrix to set of scalars.
      numNewInternalRanges <- sum(scalars)
      numExternalIndexRanges <<- length(externalRange$indexRanges)
      numInternalIndexRanges <<- length(internalRange$indexRanges)
      
      boolExternalIndexRanges <<- c(
        rep(TRUE, numExternalIndexRanges),
        rep(FALSE, numInternalIndexRanges)
      )
      decl <<- decl # pointer to governing declaration

      # Set up mappings between indexSlots and indexRanges, taking
      # mappings in externalRange and internalRange (which are local to each of those)
      # and translating to mappings on the combined set of indexRanges.

      # It is convoluted to determine the indexSlotToRange and rangeToIndexSlot
      # and then pass these into varRange initialization where indexSlotToRange will be recalculated
      # from rangeToIndexSlot.

      indexSlotToRange <<- rep(0L, length(indexSlotToSet))
      indexSlotToRange[indexSlotToSet > 0] <<- externalRange$indexSlotToRange
      indexSlotToRange[indexSlotToSet == 0] <<- internalRange$indexSlotToRange + numExternalIndexRanges 
      indexSlotToRange[indexSlotToSet < 0] <<- seq_len(numNewInternalRanges) + numExternalIndexRanges +
                                                         numInternalIndexRanges - numNewInternalRanges
      
      if (length(indexSlotToRange)) {
        rangeToIndexSlot <<- lapply(
          seq_len(max(indexSlotToRange)),
          function(x) which(indexSlotToRange == x)
        )
      } else {
        rangeToIndexSlot <- list()
      }

      super$initialize(
        indexInfo = c(externalRange$indexRanges, internalRange$indexRanges),
        rangeToIndexSlot = rangeToIndexSlot,
        varName = varName
      )
    },
    toVarRange = function() {
      varRangeClass$new(indexRanges, rangeToIndexSlot = rangeToIndexSlot, varName = varName, fromStochRule = decl$stoch)
    },

    toChar = function() {
      if (is.null(varName)) {
        nm <- as.name("no_name")
      } else {
        nm <- as.name(varName)
      }
      if (!length(indexRangeExprs)) {
        return(paste0("`", nm, "`"))
      }
      exprs <- indexRangeExprs
      multiSlot <- sapply(exprs, `==`, "...")
      sv <- exprs[boolExternalIndexRanges & !multiSlot]

      indexVars <- paste0("idx", seq_len(sum(boolExternalIndexRanges & !multiSlot)))
      exprs[boolExternalIndexRanges & !multiSlot] <- lapply(indexVars, as.name)
      forText <- paste(indexVars, "in", sv)
      result <- safeDeparse(do.call("call",
        c(
          list("[", nm),
          exprs[indexSlotToRange]
        ),
        quote = TRUE
      ))
      if (sum(boolExternalIndexRanges)) {
        if (length(sv)) {
          forText <- paste0("`, for ", paste(forText, collapse = ", "))
        } else {
          forText <- "`"
        }
        result <- paste0("`", result, forText)
      }
      return(result)
    },

    # Convert to set of character strings, one element per node,
    # i.e., format of nodes in original nimble.
    toNodeChars = function(index) {
      if (is.null(nodeChars)) {
        if (isNone()) {
          nodeChars <<- varName
        } else {
          externalIndices <- unlist(rangeToIndexSlot[boolExternalIndexRanges])
          internalIndices <- unlist(rangeToIndexSlot[!boolExternalIndexRanges])
          indicesList <- list()
          length(indicesList) <- length(indexSlotToRange)
          if (length(internalIndices)) {
            internalExprs <- sapply(indexRangeExprs[!boolExternalIndexRanges], deparse)
            for (i in seq_along(internalExprs)) {
              indicesList[[internalIndices[i]]] <- internalExprs[i]
            }
          }
          if (length(externalIndices)) {
            if (sum(boolExternalIndexRanges) == 1) {
              externalMatrix <- indexRanges[[which(boolExternalIndexRanges)]]$getValuesAsMatrix()
            } else {
              externalMatrix <- crossIndexRanges(indexRanges[boolExternalIndexRanges])$values
            } # not ordered
            tmp <- t(apply(externalMatrix, 1, as.character))
            if (ncol(externalMatrix) == 1) {
              tmp <- t(tmp)
            }
            for (i in seq_along(externalIndices)) {
              indicesList[[externalIndices[i]]] <- tmp[, i]
            }
          }
          nodeChars <<- paste0(varName, "[", do.call(pasteIndices, indicesList), "]")
        }
      }
      if (missing(index)) {
        return(nodeChars)
      } else {
        return(nodeChars[index])
      }
    },
    print = function() {
      cat("node range for ", toChar(), "\n", sep = "")
    }
  )
)

nodeRange_isEqual <- function(nr1, nr2) {
  return(identical(nr1$indexSlotToRange, nr2$indexSlotToRange) &&
    isTRUE(all.equal(nr1$indexRanges, nr2$indexRanges)) &&
    identical(nr1$boolExternalIndexRanges, nr2$boolExternalIndexRanges))
}

# Take a calcRule and fracture (split) it into one or more calcRules based on another rule.
# This is used to determine topRules, endRules, latentRules.

# Result can be:
#  - NULL if no overlap or complete overlap,
#  - a subset of the original rule and a rule created from the fracturingRange, or
#  - two subsets of original rule and a rule created from the fracturingRange
#    (when dealing with a sequence that is split)
fracture <- function(LHSrule, fracturingRange, currentID = 0, parentRule = NULL, currentRules = NULL, constants = list()) {
  # Get full nodeRange of the rule.
  LHSrange <- LHSrule$apply()

  if (!inherits(fracturingRange, "nodeRangeClass")) {
    fracturingRange <- LHSrule$apply(fracturingRange)
  }

  if (is.null(fracturingRange)) {
    return(NULL)
  }

  # Complete overlap case: set parent-child relationship.
  if (nodeRange_isEqual(LHSrange, fracturingRange)) {
    if (!is.null(parentRule)) { # if parent is not RHS
      parentRule$setChildren(LHSrule$ID)
      LHSrule$setParents(parentRule$ID)
    }
    return(NULL)
  }

  # Check which index slots use identical indexRanges and don't need to be fractured.
  # Note this should only return a subset of the external ranges as internal should be identical.
  boolIdenticalIndexSlots <- sapply(seq_along(LHSrange$indexSlotToRange), function(idx) {
    isTRUE(all.equal(
      LHSrange$indexRanges[[LHSrange$indexSlotToRange[idx]]],
      fracturingRange$indexRanges[[fracturingRange$indexSlotToRange[idx]]]
    ))
  })

  nonIdenticalIndexSlots <- which(!boolIdenticalIndexSlots)

  expr <- LHSrule$expr
  singleContexts <- LHSrule$context$singleContexts

  # Make sure we use a unique name for new indexing variable, otherwise
  # have incorrect results if first fracture on one dimension and later on a different dimension,
  # as you'd end up with `mu[.newidx, .newidx]`.
  newIdxName <- ".newidx1"
  i <- 1
  while (newIdxName %in% all.vars(expr)) {
    i <- i + 1
    newIdxName <- paste0(".newidx", i)
  }
  parsedIdxName <- parse(text = newIdxName)[[1]]

  if (length(nonIdenticalIndexSlots) == 1) {
    # Handle simple cases where need only fracture one index
    LHS <- LHSrange$indexRanges[[LHSrange$indexSlotToRange[nonIdenticalIndexSlots]]]
    frac <- fracturingRange$indexRanges[[fracturingRange$indexSlotToRange[nonIdenticalIndexSlots]]]

    focalContext <- sapply(names(singleContexts), function(nm) {
      nm %in% all.vars(expr[[2 + nonIdenticalIndexSlots]])
    })

    if (sum(focalContext) != 1) {
      stop("unexpected number of contexts in `", safeDeparse(expr), "`.")
    }

    # General strategy in cases below is to determine overlapped and non-overlapped
    # index values and create new calcRules for these, modifying the
    # expression, contexts, and constants from the LHS rule.

    # If matrix involved, we need to create resulting rules as indexRuleArbitraryClass.
    if (inherits(LHS, "indexRangeMatrixClass") || inherits(frac, "indexRangeMatrixClass")) {
      # `as.numeric` prevents some indexRanges from having ints when generally have doubles.
      valsLHS <- switch(class(LHS)[1],
        indexRangeMatrixClass = LHS$values,
        indexRangeScalarClass = LHS$value,
        indexRangeSequenceClass = as.numeric(LHS$start:LHS$end),
        stop("`LHS` type not found.")
      )
      valsFrac <- switch(class(frac)[1],
        indexRangeMatrixClass = frac$values,
        indexRangeScalarClass = frac$value,
        indexRangeSequenceClass = as.numeric(frac$start:frac$end),
        stop("`frac` type not found.")
      )
      valsLHS <- valsLHS[!valsLHS %in% valsFrac] # Values for new rule are those that don't overlap.

      if (!length(valsLHS)) { # Full overlap (not caught previously if, e.g., LHS is seq and fracturer is matrix).
        if (!is.null(parentRule)) { # If parent is not RHS.
          parentRule$setChildren(LHSrule$ID)
          LHSrule$setParents(parentRule$ID)
        }
        return(NULL)
      }

      # Modify LHSrule expr and context to insert vector of relevant values for
      # one rule with non-overlapped index values and one rule with overlapped values.
      newSingleContexts1 <- singleContexts[!focalContext]
      newSingleContexts2 <- singleContexts[!focalContext]

      newSingleContexts1[[length(newSingleContexts1) + 1]] <- singleContextClass$new(
        indexVarExpr = parsedIdxName,
        indexRangeExpr = substitute(1:L, list(L = length(valsLHS)))
      )

      newSingleContexts2[[length(newSingleContexts2) + 1]] <- singleContextClass$new(
        indexVarExpr = parsedIdxName,
        indexRangeExpr = substitute(1:L, list(L = length(valsFrac)))
      )

      newcode <- paste0(".idx", nonIdenticalIndexSlots, "[", newIdxName, "]")
      expr[[nonIdenticalIndexSlots + 2]] <- parse(text = newcode[1])[[1]]

      # Replace any constants related to a previously processed index slot.
      # Index values are stored in an element of `constants`.
      constants1 <- list(valsLHS)
      constants2 <- list(valsFrac)
      names(constants1) <- paste0(".idx", nonIdenticalIndexSlots)
      names(constants2) <- paste0(".idx", nonIdenticalIndexSlots)
      oldConstants <- constants
      oldConstants[names(oldConstants) %in% names(constants1)] <- NULL

      resultRule <- calcRuleClass$new(LHSrule$declRule, expr, currentID + 1,
        context = modelContextClass$new(newSingleContexts1),
        constants = c(constants1, oldConstants)
      )

      fracturingRule <- calcRuleClass$new(LHSrule$declRule, expr, currentID + 2,
        context = modelContextClass$new(newSingleContexts2),
        constants = c(constants2, oldConstants)
      )

      result <- list(fracturingRule, resultRule)
    } else { # Two sequences or sequence and a scalar, handled by creating new sequences.
      if (inherits(frac, "indexRangeScalarClass")) { # Process as a sequence to avoid special casing.
        frac <- newIndexRange(substitute(A:A, list(A = frac$value)))
      }
      # Scalar LHS should either have no overlap or full overlap and have been handled at start.
      if (inherits(LHS, "indexRangeScalarClass")) {
        stop("not expecting `LHS` to be a scalar.")
      }

      if (frac$start == LHS$start || frac$end == LHS$end) {
        # Shrink existing sequence.
        # Don't modify LHS as it is an indexRange pointing to memory in `rhsOriginalRules`.
        start <- LHS$start
        end <- LHS$end
        if (frac$start == LHS$start) {
          start <- frac$end + 1
        } else {
          end <- frac$start - 1
        }

        newSingleContexts1 <- singleContexts[!focalContext]
        newSingleContexts2 <- singleContexts[!focalContext]

        newSingleContexts1[[length(newSingleContexts1) + 1]] <- singleContextClass$new(
          indexVarExpr = parsedIdxName,
          indexRangeExpr = substitute(A:B, list(A = start, B = end))
        )

        newSingleContexts2[[length(newSingleContexts2) + 1]] <- singleContextClass$new(
          indexVarExpr = parsedIdxName,
          indexRangeExpr = substitute(A:B, list(A = frac$start, B = frac$end))
        )

        expr[[nonIdenticalIndexSlots + 2]] <- newSingleContexts1[[length(newSingleContexts1)]]$indexVarExpr

        fracturingRule <- calcRuleClass$new(LHSrule$declRule, expr, currentID + 1,
          context = modelContextClass$new(newSingleContexts2),
          constants = constants
        )
        resultRule <- calcRuleClass$new(LHSrule$declRule, expr, currentID + 2,
          context = modelContextClass$new(newSingleContexts1),
          constants = constants
        )

        result <- list(fracturingRule, resultRule)
      } else {
        # Split an existing sequence.
        newSingleContexts1 <- singleContexts[!focalContext]
        newSingleContexts2 <- singleContexts[!focalContext]
        newSingleContexts3 <- singleContexts[!focalContext]

        expr1 <- expr2 <- expr3 <- expr
        newSingleContexts1[[length(newSingleContexts1) + 1]] <- singleContextClass$new(
          indexVarExpr = parsedIdxName,
          indexRangeExpr = substitute(A:B, list(A = frac$start, B = frac$end))
        )
        expr1[[nonIdenticalIndexSlots + 2]] <- newSingleContexts1[[length(newSingleContexts1)]]$indexVarExpr

        newSingleContexts2[[length(newSingleContexts2) + 1]] <- singleContextClass$new(
          indexVarExpr = parsedIdxName,
          indexRangeExpr = substitute(A:B, list(A = LHS$start, B = frac$start - 1))
        )
        expr2[[nonIdenticalIndexSlots + 2]] <- newSingleContexts2[[length(newSingleContexts2)]]$indexVarExpr

        newSingleContexts3[[length(newSingleContexts3) + 1]] <- singleContextClass$new(
          indexVarExpr = parsedIdxName,
          indexRangeExpr = substitute(A:B, list(A = frac$end + 1, B = LHS$end))
        )
        expr3[[nonIdenticalIndexSlots + 2]] <- newSingleContexts3[[length(newSingleContexts3)]]$indexVarExpr

        fracturingRule <- calcRuleClass$new(LHSrule$declRule, expr1, currentID + 1,
          context = modelContextClass$new(newSingleContexts1),
          constants = constants
        )
        resultRule1 <- calcRuleClass$new(LHSrule$declRule, expr2, currentID + 2,
          context = modelContextClass$new(newSingleContexts2),
          constants = constants
        )
        resultRule2 <- calcRuleClass$new(LHSrule$declRule, expr3, currentID + 3,
          context = modelContextClass$new(newSingleContexts3),
          constants = constants
        )

        result <- list(fracturingRule, resultRule1, resultRule2)
      }
    }
  } else { # Unroll, exclude, create new arbitrary rule based on all non-identical indices.
    unrolledLHS <- LHSrange$extractIndexRange(nonIdenticalIndexSlots)
    unrolledFrac <- fracturingRange$extractIndexRange(nonIdenticalIndexSlots)

    # Convert to character representation to allow simplest determination of overlap/non-overlap,
    # using all index
    lhsAsChar <- do.call(paste, as.data.frame(unrolledLHS$values))
    fracAsChar <- do.call(paste, as.data.frame(unrolledFrac$values))

    remaining <- !lhsAsChar %in% fracAsChar
    mat1 <- unrolledLHS$values[remaining, , drop = FALSE]
    mat2 <- unrolledLHS$values[!remaining, , drop = FALSE]

    if (!length(mat1)) {
      # Full overlap; this should not be needed, but just in case
      # (e.g., if LHS and fracturer elements are somehow not in same order).
      if (!is.null(parentRule)) { # If parent is not RHS.
        parentRule$setChildren(LHSrule$ID)
        LHSrule$setParents(parentRule$ID)
      }
      return(NULL)
    }

    focalContext <- sapply(names(singleContexts), function(nm) {
      nm %in% unlist(lapply(2 + nonIdenticalIndexSlots, function(x) all.vars(expr[[x]])))
    })

    # Handle any contexts involving identical indices.
    if (sum(!focalContext)) {
      newSingleContexts1 <- singleContexts[!focalContext]
      newSingleContexts2 <- singleContexts[!focalContext]
    } else {
      newSingleContexts1 <- newSingleContexts2 <- list()
    }

    newSingleContexts1[[length(newSingleContexts1) + 1]] <- singleContextClass$new(
      indexVarExpr = parsedIdxName,
      indexRangeExpr = substitute(1:L, list(L = nrow(mat1)))
    )

    newSingleContexts2[[length(newSingleContexts2) + 1]] <- singleContextClass$new(
      indexVarExpr = parsedIdxName,
      indexRangeExpr = substitute(1:L, list(L = nrow(mat2)))
    )

    newcode <- paste0(".idx", nonIdenticalIndexSlots, "[", newIdxName, "]")
    for (i in seq_along(nonIdenticalIndexSlots)) {
      expr[[nonIdenticalIndexSlots[i] + 2]] <- parse(text = newcode[i])[[1]]
    }

    # Store index values in elements of `constants`, one per non-identical index slot.
    constants1 <- lapply(seq_len(ncol(mat1)), function(i) mat1[, i])
    names(constants1) <- paste0(".idx", nonIdenticalIndexSlots)
    constants2 <- lapply(seq_len(ncol(mat2)), function(i) mat2[, i])
    names(constants2) <- paste0(".idx", nonIdenticalIndexSlots)
    oldConstants <- constants
    oldConstants[names(oldConstants) %in% names(constants1)] <- NULL

    fracturingRule <- calcRuleClass$new(LHSrule$declRule, expr, currentID + 1,
      context = modelContextClass$new(newSingleContexts2),
      constants = c(constants2, oldConstants)
    )
    resultRule <- calcRuleClass$new(LHSrule$declRule, expr, currentID + 2,
      context = modelContextClass$new(newSingleContexts1),
      constants = c(constants1, oldConstants)
    )

    result <- list(fracturingRule, resultRule)
  }

  names(result) <- sapply(result, function(rule) rule$ID)

  # Set parent-child links based on newly-create rules.
  if (!is.null(parentRule)) { # Only need to do if parent is not from a rhsRule.

    if (parentRule$ID != LHSrule$ID) {
      # Condition ensures we don't set child-parent pair based on parent itself being
      # fractured, as occurs in state-space type cases.

      # Set fracturingRule (always `result[[1]]`) and parentRule as child-parent pair.
      result[[1]]$setParents(parentRule$ID)
      parentRule$setChildren(result[[1]]$ID)
    }

    # Set parents of fractured results to be the original parents of fractured (LHS) rule.
    sapply(result, function(rule) rule$setParents(LHSrule$parents))

    # Update children of parents of the fractured (LHS) rule to be
    # new fractured results and not fractured (LHS) rule.
    newChildren <- sapply(result, function(x) x$ID)
    names(newChildren) <- NULL
    sapply(LHSrule$parents, function(idx) {
      currentRules[[idx]]$setChildren(newChildren)
    })
    sapply(LHSrule$parents, function(idx) {
      currentRules[[idx]]$unsetChildren(LHSrule$ID)
    })
  }
  # Remove fractured (LHS) rule as parent of its children.
  # The new fractured rules will be added in as parents when they are used as fracturers,
  # later in looping over calcRules.
  sapply(LHSrule$children, function(idx) {
    currentRules[[idx]]$unsetParents(LHSrule$ID)
  })
  return(result)
}

# Sets parent-child link based on a dependent of `parentRule`
# overlapping with `LHSrule`.
checkAndCreateLink <- function(LHSrule, dependentRange, parentRule) {
  overlapRange <- LHSrule$apply(dependentRange)
  if (!is.null(overlapRange)) {
    # Any intersection means we need to set parent/child relationship.
    parentRule$setChildren(LHSrule$ID)
    LHSrule$setParents(parentRule$ID)
  }
  invisible(NULL)
}

# Two use cases:
# 1) Takes a RHS rule (created from variable used in original RHS of an expression) and intersects it with another rule,
# which could be a `rhsRule` or a `declRule`, from use of the variable either on the LHS or the RHS.
# 2) Takes a focal rule and intersects it with another rule, for excluding candidate calcRules from predictiveRules.
# Result can be:
#  - no intersection: focal rule passed through,
#  - focal is fully in excluding rule: result is NULL, or
#  - partly intersects: fracture and return one or more fractured rules.

exclude <- function(focalRule, excludingRule, constants = list()) {
  # Can also take varRanges for use in `traverseGraph`.
  if (inherits(excludingRule, "varRangeClass")) {
    excludingRange <- excludingRule
  } else {
    excludingRange <- excludingRule$fullRange
  }
  if (inherits(focalRule, "varRangeClass")) {
    focalRange <- focalRule
    focalRule <- focalRule$toRule()
  } else {
    focalRange <- focalRule$fullRange
  }
  intersection <- focalRule$apply(excludingRange)

  if (is.null(intersection)) { # no overlap
    return(list(focalRule))
  }
  if (varRange_isEqual(focalRange, intersection)) { # full overlap
    return(NULL)
  }

  # Partial overlap case. We need to fracture the focalRule.

  identicalIndices <- sapply(seq_along(focalRange$indexSlotToRange), function(idx) {
    isTRUE(all.equal(
      focalRange$indexRanges[[focalRange$indexSlotToRange[idx]]],
      intersection$indexRanges[[intersection$indexSlotToRange[[idx]]]]
    ))
  })

  nonIdenticalIndices <- which(!identicalIndices)

  expr <- focalRule$expr
  singleContexts <- focalRule$context$singleContexts

  if (length(focalRule$fullRule$indexSets$toIndexSlotToSet) == 1 || length(nonIdenticalIndices) == 1) {
    # TODO: remove this check when have done full testing and presumably simply above to only check 2nd condition.
    if (length(focalRule$fullRule$indexSets$toIndexSlotToSet) == 1 && length(nonIdenticalIndices) != 1) {
      stop("DEBUG: check.")
    }

    # split, shrink, or remove from focal index, and combine with other indices
    RHS <- focalRange$indexRanges[[focalRange$indexSlotToRange[nonIdenticalIndices]]]
    int <- intersection$indexRanges[[intersection$indexSlotToRange[nonIdenticalIndices]]]

    focalContext <- sapply(names(singleContexts), function(nm) {
      nm %in% all.vars(expr[[2 + nonIdenticalIndices]])
    })

    if (inherits(RHS, "indexRangeMatrixClass") || inherits(int, "indexRangeMatrixClass")) {
      # Handle any matrix cases by expanding elements.
      valsRHS <- switch(class(RHS)[1],
        indexRangeMatrixClass = RHS$values,
        indexRangeScalarClass = RHS$value,
        indexRangeSequenceClass = as.numeric(RHS$start:RHS$end),
        stop("`RHS` type not found.")
      )
      valsInt <- switch(class(int)[1],
        indexRangeMatrixClass = int$values,
        indexRangeScalarClass = int$value,
        indexRangeSequenceClass = as.numeric(int$start:int$end),
        stop("`int` type not found.")
      )
      valsRHS <- valsRHS[!valsRHS %in% valsInt]

      # Modify focalRule expr and context to insert vector of relevant values.
      newSingleContexts <- singleContexts[!focalContext]
      newSingleContexts[[length(newSingleContexts) + 1]] <- singleContextClass$new(
        indexVarExpr = quote(.newidx),
        indexRangeExpr = substitute(1:L, list(L = length(valsRHS)))
      )

      newcode <- paste0(".idx", nonIdenticalIndices, "[.newidx]")
      expr[[nonIdenticalIndices + 2]] <- parse(text = newcode[1])[[1]]

      # Replace any constants related to an index slot processed in a previous
      # call to `exclude`.
      constants <- list(valsRHS)
      names(constants) <- paste0(".idx", nonIdenticalIndices)
      oldConstants <- constants
      oldConstants[names(oldConstants) %in% names(constants)] <- NULL

      if (inherits(focalRule, "rhsRuleClass")) {
        resultRule <- rhsRuleClass$new(expr,
          context = modelContextClass$new(newSingleContexts),
          constants = c(constants, oldConstants), usedInIndex = focalRule$usedInIndex
        )
      } else {
        resultRule <- calcRuleClass$new(focalRule$declRule, expr,
          ID = focalRule$ID,
          context = modelContextClass$new(newSingleContexts),
          constants = c(constants, oldConstants)
        )
      }
      return(list(resultRule))
    } else { # seq+seq or seq+scalar
      if (inherits(int, "indexRangeScalarClass")) { # convert to sequence to avoid special case code
        int <- newIndexRange(substitute(A:A, list(A = int$value)))
      }
      if (inherits(RHS, "indexRangeScalarClass")) {
        stop("not expecting RHS to be a scalar.")
      } # scalar RHS either fully intersected or not intersected

      # Now process two sequences.
      if (int$start == RHS$start || int$end == RHS$end) {
        # Shrink existing index block.
        # Don't modify RHS as it is an indexRange pointing to memory in `rhsOriginalRules`.
        start <- RHS$start
        end <- RHS$end
        if (int$start == RHS$start) {
          start <- int$end + 1
        } else {
          end <- int$start - 1
        }

        newSingleContexts <- singleContexts[!focalContext]
        newSingleContexts[[length(newSingleContexts) + 1]] <- singleContextClass$new(
          indexVarExpr = quote(.newidx),
          indexRangeExpr = substitute(A:B, list(A = start, B = end))
        )
        expr[[nonIdenticalIndices + 2]] <- newSingleContexts[[length(newSingleContexts)]]$indexVarExpr

        if (inherits(focalRule, "rhsRuleClass")) {
          resultRule <- rhsRuleClass$new(expr,
            context = modelContextClass$new(newSingleContexts),
            constants = constants, usedInIndex = focalRule$usedInIndex
          )
        } else {
          resultRule <- calcRuleClass$new(focalRule$declRule, expr,
            ID = focalRule$ID,
            context = modelContextClass$new(newSingleContexts),
            constants = constants
          )
        }
        return(list(resultRule))
      } else {
        # Modify focalRule expr and context to create two new rules.
        newSingleContexts1 <- singleContexts[!focalContext]
        newSingleContexts2 <- singleContexts[!focalContext]

        expr1 <- expr2 <- expr
        newSingleContexts1[[length(newSingleContexts1) + 1]] <- singleContextClass$new(
          indexVarExpr = quote(.newidx),
          indexRangeExpr = substitute(A:B, list(A = RHS$start, B = int$start - 1))
        )
        expr1[[nonIdenticalIndices + 2]] <- newSingleContexts1[[length(newSingleContexts1)]]$indexVarExpr

        newSingleContexts2[[length(newSingleContexts2) + 1]] <- singleContextClass$new(
          indexVarExpr = quote(.newidx),
          indexRangeExpr = substitute(A:B, list(A = int$end + 1, B = RHS$end))
        )
        expr2[[nonIdenticalIndices + 2]] <- newSingleContexts2[[length(newSingleContexts2)]]$indexVarExpr

        if (inherits(focalRule, "rhsRuleClass")) {
          resultRule1 <- rhsRuleClass$new(expr1,
            context = modelContextClass$new(newSingleContexts1),
            constants = constants, usedInIndex = focalRule$usedInIndex
          )
          resultRule2 <- rhsRuleClass$new(expr2,
            context = modelContextClass$new(newSingleContexts2),
            constants = constants, usedInIndex = focalRule$usedInIndex
          )
        } else {
          resultRule1 <- calcRuleClass$new(focalRule$declRule, expr1,
            ID = focalRule$ID,
            context = modelContextClass$new(newSingleContexts1),
            constants = constants
          )
          resultRule2 <- calcRuleClass$new(focalRule$declRule, expr2,
            ID = focalRule$ID,
            context = modelContextClass$new(newSingleContexts2),
            constants = constants
          )
        }
        return(list(resultRule1, resultRule2))
      }
    }
  } else {
    # Scenarios that are not the simple setting of a single index slot that needs to be considered.
    # Create fully unrolled matrix of indices for non-identical indices, do exclusion,
    # then create new arbitrary focalRule by creating a complicated context, crossed with any indices that are identical
    unrolledRHS <- focalRange$extractIndexRange(nonIdenticalIndices)
    unrolledIntersection <- intersection$extractIndexRange(nonIdenticalIndices)

    # Convert matrices of index values by row to strings to allow matching.
    rhsAsChar <- do.call(paste, as.data.frame(unrolledRHS$values))
    intAsChar <- do.call(paste, as.data.frame(unrolledIntersection$values))

    remaining <- !rhsAsChar %in% intAsChar
    remainingVals <- unrolledRHS$values[remaining, , drop = FALSE]

    # Retain singleContexts for identical indices.
    focalSingleContexts <- sapply(names(singleContexts), function(nm) {
      nm %in% unlist(lapply(2 + nonIdenticalIndices, function(x) all.vars(expr[[x]])))
    })
    if (sum(!focalSingleContexts)) {
      newSingleContexts <- singleContexts[!focalSingleContexts]
    } else {
      newSingleContexts <- list()
    }

    newSingleContexts[[length(newSingleContexts) + 1]] <- singleContextClass$new(
      indexVarExpr = quote(.newidx),
      indexRangeExpr = substitute(1:L, list(L = nrow(remainingVals)))
    )

    newcode <- paste0(".idx", nonIdenticalIndices, "[.newidx]")
    for (i in seq_along(nonIdenticalIndices)) {
      expr[[nonIdenticalIndices[i] + 2]] <- parse(text = newcode[i])[[1]]
    }

    # Replace any constants related to an index slot processed in a previous
    # call to `exclude`.
    oldConstants <- constants
    constants <- lapply(seq_len(ncol(remainingVals)), function(i) remainingVals[, i])
    names(constants) <- paste0(".idx", nonIdenticalIndices)
    oldConstants[names(oldConstants) %in% names(constants)] <- NULL
    if (inherits(focalRule, "rhsRuleClass")) {
      resultRule <- rhsRuleClass$new(expr,
        context = modelContextClass$new(newSingleContexts),
        constants = c(constants, oldConstants), usedInIndex = focalRule$usedInIndex
      )
    } else {
      resultRule <- calcRuleClass$new(focalRule$declRule, expr,
        ID = focalRule$ID,
        context = modelContextClass$new(newSingleContexts),
        constants = c(constants, oldConstants)
      )
    }
    return(list(resultRule))
  }
}
