---
title: "calculation processing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Model preprocessing:

- Each declaration should produce one or more `calcRule`s for the LHS variable, where there is one `calcRule` for each unique sortID in the sortIDs corresponding to the `varRange` of the LHS variable.

- Each declaration will have multiple calculate functions, potentially allowing for various types of vectorized calculations (pure nimble vectorization, Eigen vectorization, looping over sets, looping over blocks)

Roughly the order of operations when calculate is invoked is

- User asks for calculation on a set of `varRange`s, either by specifying them directly or asking for dependencies and thereby inducing `graphRule` processing
- For each `varRange`, all `calcRule`s for the variable are checked and one or more `calcRange`s are returned.
- Multiple `calcRange`s can be sorted based on their sort ID and then full calculation can be done.

