---
title: "implementation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Implementation of graph, index, and calculation relationships.

- An `indexRange` manages the index content of one dimension of one variable.

    - This is implemented as a list, with attributes for `class` and `rangeType`
    - `rangeType`s include sequence (`1:10`), vector (arbitrary), scalar, and blank.

- An `indexRule` manages the determination of LHS indices from RHS indices for one or more `indexRange`s.  (Sometimes multiple index dimensions needs to be solved jointly.)

    - Kinds of `indexRule`s include block and arbitrary.
    - Inputs and outputs to application of an `indexRule` may be an `indexRange` and/or `varRange` (somewhat TBD).
    - Inputs that are out of range do not produce output
    - Includes checks for going out of range
    - By reversing the order of a declaration, we can create both parent and child rules
    - Consider all possibilities of LHS blank, constant, vector/block and RHS blank, constant, vector/block.

- An `originalIndexRule` manages the determination of nodeFunction indices from actual index values, e.g., with a declaration such as `y[i+1] <- x[i]`, determining that calculation for `y[2]` is handled with `i=1`.

    - This can be handled with the `indexRule` functionality by making dummy declarations such as `w[i,j] <- y[i+j]` if the focal declaration is, say, `y[i+j] <- x[i] + x[j]`.

- A `varRange` manages a set of `indexRange`s representing all dimensions of a variable.

    - A `varRange` also keeps track of how each `indexRange` would be crossed or combined with others to represent the set of variable elements correctly.
    - Ultimately we may want to be able to [collapse multiple `varRange`s to a single `varRange`](combining_ranges.html) when possible.

- A `graphRule` manages the set of `indexRule`s needed to determine all LHS indices from all RHS indices for one set of edges created one of the RHS variables and the LHS variable of a single declaration.

    - Inputs and outputs to a `graphRule` are `varRange`s.
    
- A `varRules` manages the set of `graphRule`s for the same variable (RHS).

- A `calcRange` manages the indexing for a single calculation for a variable

    - Keeps track of declaration ID, indexing (probably using `indexRange`s), index values, and nodeFunction version to be used.
    - Index values are based on original declaration context, e.g., a declaration of `y[i+1] ~ dnorm(x[i], 1)` with `i=1:5` has `calcRange` indexing of `1:5` since nodeFunctions use `i` directly. 
    - Includes sort ID so that multiple `calcRange`s can be calculated in correct order.
    - Eventually might deal with doing calcs that don't have complete sort ties, e.g., `y[i]~dfoo(y[i-1])`, as a block but probably not to start.
    - Indexing is over nodes.

- A `calcRule` manages a single `varRange` that can be calculated jointly.

    - An individual `calcRule` is produced from the elements in a declaration that are tied in terms of their sort order.
    - When passed another `varRange` it returns a `calcRange` (or nothing if there is no overlap between the input `varRange` and the `varRange` of the rule) that can be used for calculation.
    - Contains `originalIndexRule`s to relate back to original index values in the declaration context.
       - Indexing is based on indexes of the variable, not the original index values, e.g., `y[i+1] ~ dnorm(x[i], 1)` with `i=1:5` has the `varRange` of `y[2:6]`. 
    - Contains the sort ID for the `varRange`.
    - May be associated with types such as 'end','top', etc. since those will relate directly to sort ID.
    - Perhaps produced from original nodeRules and fracturing of those rules based on walking down the graph.
    - Inherits density calculation from original nodeRule it is created from.
    - Indexing is over nodes.

- A `varCalcRules` manages the set of `calcRule`s for a given variable.

- (Tentative) originalNodeRules and fracturedNodeRules could all be of type nodeRule, with varCalcRules just a list of the fracturedNodeRules and the originalNodeRules that were never fractured.

- A `nodeRule` manages a single set of nodes from a declaration that are equivalent in some sense. Given a `varRange`, it produces a `nodeRange` (or nothing if no overlap). 

    - Input is a `varRange`.
    - Output is a `nodeRange`.
    - Created by initial pass through model, with LHS from the declarations
    - (Possibly deprecated) "Equivalent" needs to be defined:
       - Could be nodes declared in the same way, possibly with identical sort ID (perhaps only identical when considered at the `calcRule` level, so could have lack of ties for 'internal' dependence such as state-space cases).
       - Could be nodes all of the same type (noting that `theta[i] ~ dnorm(theta0[i], 1)` are not necessarily all latent or all top nodes, as it depends on how `theta0[i]` are declared; this would involve splitting an original `nodeRule` when graph processing is done.
       - Potentially handle both with polymorphism/nested structures
       - A single `nodeRule` is associated with a single nodeFunction (i.e., one `calcRule`, but multiple `nodeRule`s could potentially be associated with the same `calcRule` -- see case above).
    - (Tentative - 2022-03-25) nodeRules may be simply based on original declarations with "equivalent" business pushed onto the `calcRule`s.
    - Contains `originalIndexRule` to pass along to constituent `calcRule`s.
    - Could represent the 'canonical' set of equivalent nodes as an embedded `nodeRange`
    - If not fractured, could also be the `calcRule` itself?
    - Indexing is over nodes (see comments below regarding `nodeRange`.

- A `nodeRange` compactly represents a set of equivalent nodes

    - E.g., `y[i, 1:3] for i in 1:500` or `y[i, j] for i in 1:5, j in 1:20`
    - Not equivalent to a `varRange` as `y[i, 1:3] for i in 1:500` is a `nodeRange` while `y[1:500, 1:3]` is a `varRange`
       - Contains the internalRange (e.g., `1:3`) and the nodeRange (e.g, `1:500`); probably want a different name for the embedded 'nodeRange'
    - Currently contains a `getVarRange` method that converts to the equivalent varRange.
    - Perhaps printed representation is `y[1:500, (1:3)]`, where (..) represents the 'internal' block.

- A `copyRule` manages the determination of copying for a variable

    - presumably trivial but a bit fuzzy at the moment
    - Input is a `varRange`?
    - Output is a `varRange`.
    - Perhaps all it needs to do is check for out of bounds and expand missing indexes?

- (Deprecated?) A `variableStore` manages array-like information for variables (see below for alternative idea of using `varTypeRule`s)

    - Stores information such as sort ID, isData, node types
    - Could be integer, logical, or character-valued
    - Should efficiently handle case where all values are the same
    - Ultimately may want to handle additional structure, such as blocks of equal values
       - Could have sets of blocks, with remaining values a "discontinuous block" if all the same.
    - Ultimately may want to handle simple sequential values (e.g., row-major or column-major in a matrix) as this could be useful for sort ID values in state-space/time-series contexts.
    - Should we have `variableStore`s that map back to `calcRule`s and `nodeRule`s? This might avoid need to store something like node type if all node types for a given `nodeRule` are the same. Also avoids need for variable-level sort ID unless there is an ordering with a given `calcRule` (since could just look up sort ID of the `calcRule`).

- (Tentative - 2022-03-25) `nodeTypeRule`s manage information about node types such as end, RHS, latent, top, stochastic, deterministic, etc.
    - May simply be a `calcRule` or derived from it, but with associated information about type.
    - `RHSonly` found by fracturing original RHS rules based on LHS rules
    - `top` found by walking down the graph (from known `top` [those with only constant RHS] and `RHSonly`), fracturing, and tagging what has stoch parents; the fractured (or original) rules that don't have stoch parents are `top`
    - `end` found by starting with fractured rules with no dependents. Then also walk up from each stoch end rule and anything found along the way is removed from being `end`
    - `latent` found by what is not top or end

- (Tentative - 2022-03-18) A `varTypeRule`s manages information about node types such as end, RHS, latent, top, stochastic, deterministic, etc.
    - Given a `varRange`, a `varTypeRule` for, say, `top` nodes returns a `varRange` (or perhaps equivalent `nodeRange`) containing the subset of variable elements that are `top`. Similarly for other types.
    - This avoids having to store information in `variableStore`s and can use all of our tools for working with `indexRange`s and `varRange`s.
    - How do we determine nodeTypes? Possible sketch:
       - Set up `RHS`, `top`, and `end` `varTypeRule`s based on, respectively, RHS, LHS and LHS of a declaration in first pass. (i.e., everything on LHS starts out as both `top` and `end`).
       - In second pass:
             - split `end` rules such that any part appearing in a RHS is assigned 'latent' and what remains is `end`.
             - split out `top` rules such that any part that is dependency of `top` or `latent` is excluded.
             - may not need to split `RHS` as `includeRHSonly` determination can be done via passing through a `RHS` varTypeRule, albeit giving some redundant information.
       - Need to be able to do processing of indexRanges that splits them into two ranges - what is included and what is excluded.
             - Inclusion should retain sequence indexRanges, but exclusion will in some cases need to create matrix indexRanges, probably via unrolling.

- `varTopRules`, `varEndRules`, `varStochRules`, etc. manage the set of `varTypeRules`s for a given type and variable.

- There will be multiple `nodeFunction`s for a given declaration, allowing for various types of vectorized calculations.

- Topological sorting needs to:

    - create a sort ID for each element of each variable (for tracking dependencies), stored in a `variableStore`.
    - also create sort IDs in the 'original index space' - probably this just means assigning a sort ID to each `calcRule`
       - These sort IDs can be generated as `calcRule`s are created based on sort ID of each child `varRange` in a declaration being the minimum of the sort IDs of the parent `varRange`s in the declaration minus 1. Will need repeated passes through the `calcRule`s until all sort IDs are known. 
    - sort IDs for each element would probably be nested within `calcRule` sort IDs. I.e., one `calcRule` precedes or is tied with another `calcRule` and then calculation of variable elements within a `calcRule` may have to have to be done in a particular order by referencing the `variableStore` containing the nested sort IDs for a given `varRange`.

- Dynamic indexing still needs consideration.

    - Currently we introduce a hidden 'unknownIndex' lifted node that allows for our standard dependency processing.
    - Possibly handle things similarly to current approach: have one `graphRule` with `varRange` of the 'unknownIndex' as the LHS and another `graphRule` with `varRange` of the 'unknownIndex' as the RHS.
