---
title: "model processing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here are the key steps in creating a model definition using the new framework. Some of this mimics steps in current modelDef processing.

- Process if-then-else.
- Set up dimensions.
- Determine declarations and contexts via `processModelCode`.
- Handle bounds and truncation.
- Handle parameterizations and links.
- Create `declRule`s and set up symbolic parent nodes *at the declaration level*.
- Create RHS original rules (before determining what is RHS *only*).
- Make individual upstream and downstream `graphRule`s (using `symbolicParentNodes`) *at the declaration level* via `makeGraphRules`.
- Create sets of `declRule`s, upstream and downstream `graphRule`s, `calcRule`s of various types (`end`, `top`, etc.), `rhsOnlyRule`s *at the model level* via `makeGraphInfo`.
   - This has somewhat sophisticated but ugly code for dealing with state-space structures reasonably efficiently for many cases.
